// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/audit.proto

package go_app

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Audit is one write that happened, and who made it.
//
// A row is written by `server/audit` for every request that changed something,
// in the transaction that changed it, so the trail and the data it is about
// hold or fall together. Nothing writes one by hand: the RPCs below exist so
// that a test can arrange a trail and read it back, and the deployment refuses
// the ones that write; see `audit.Server`.
type Audit struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_TenantId    []byte                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ActorId     []byte                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId"`
	xxx_hidden_TraceId     []byte                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId"`
	xxx_hidden_Action      string                 `protobuf:"bytes,5,opt,name=action"`
	xxx_hidden_ObjectId    []byte                 `protobuf:"bytes,6,opt,name=object_id,json=objectId"`
	xxx_hidden_Patch       []byte                 `protobuf:"bytes,7,opt,name=patch"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_go_app_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Audit) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Audit) GetTenantId() []byte {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return nil
}

func (x *Audit) GetActorId() []byte {
	if x != nil {
		return x.xxx_hidden_ActorId
	}
	return nil
}

func (x *Audit) GetTraceId() []byte {
	if x != nil {
		return x.xxx_hidden_TraceId
	}
	return nil
}

func (x *Audit) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *Audit) GetObjectId() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectId
	}
	return nil
}

func (x *Audit) GetPatch() []byte {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *Audit) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Audit) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Audit) SetTenantId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TenantId = v
}

func (x *Audit) SetActorId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ActorId = v
}

func (x *Audit) SetTraceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TraceId = v
}

func (x *Audit) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *Audit) SetObjectId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectId = v
}

func (x *Audit) SetPatch(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Patch = v
}

func (x *Audit) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Audit) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Audit) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Audit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// The Tenant the caller was held by, which is who this was done on behalf
	// of. It is not the Tenant of the thing that changed: whoever administers
	// the deployment may write into any of them, and what an audit trail is
	// asked about first is who did it.
	//
	// So this trail is the actor's and not the object's, and two things follow.
	// A row is stamped with the Tenant that was acting and nothing moves it
	// afterwards, so a thing that is later transferred to another Tenant leaves
	// its whole trail behind -- which is the conservative reading, since
	// receiving something does not come with the right to read what its previous
	// owner did inside their own walls. And a Tenant does not see what was done
	// to its own rows from outside it: root writing into acme leaves a row that
	// is root's to read.
	//
	// Closing that second half means recording the Tenant of the *object* as
	// well, at the time of the write, and it is deliberately not done. The
	// recorder is told about a write after it has happened, and by then an Erase
	// has taken the row it would have read; making it available would mean
	// either eagerly loading every edge of every entity on every Erase, in a
	// generator that serves more than this app, or recording before the write is
	// known to have happened. A column that is right for three RPCs and missing
	// for the fourth is worse than no column.
	TenantId []byte
	// The Holder that made the request. It is the zero identifier for a write
	// nobody asked for, which is what the deployment does to itself at startup;
	// see `core.EnsureRoot`.
	ActorId []byte
	// The trace the request belonged to, empty if it was not traced. It is 16
	// bytes as OpenTelemetry spells one, which is not a UUID however alike they
	// look, so it is stored as what it is.
	TraceId []byte
	// The RPC that did it, by the name gRPC knows it by, such as
	// "/go_app.HolderService/Apply".
	Action string
	// What changed, by its identifier. That is the whole of what "the history of
	// this thing" is asked with, and it is the index below.
	//
	// Which kind of thing it was is not stored, because an identifier is unique
	// across every one of them: whatever answers to it is what the row is about.
	//
	// The cost is that a row erased later leaves an identifier nothing answers
	// to, and no way to say what it used to be. It is why a Holder is erased
	// softly: almost every row here names one in `actor_id`, so a Holder that was
	// deleted would leave this trail saying who while nobody could find out who.
	// A Tenant is still erased for real, so a row about one erased since is an
	// identifier and a shrug -- which is what this cost looks like when it is
	// not paid.
	ObjectId []byte
	// The patch document the write was compiled from, as it was marshaled, and
	// empty for a write that was not one -- an Add or an Erase says everything
	// it did in `action` and `object_id`.
	//
	// It is stored as bytes rather than read back as a document, because that is
	// what an audit trail is for: it is written once and read by somebody asking
	// what happened, and whoever asks can unmarshal it. A column of its own per
	// operation would be a second schema to keep in step with the first.
	Patch       []byte
	DateCreated *timestamppb.Timestamp
}

func (b0 Audit_builder) Build() *Audit {
	m0 := &Audit{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_ActorId = b.ActorId
	x.xxx_hidden_TraceId = b.TraceId
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_ObjectId = b.ObjectId
	x.xxx_hidden_Patch = b.Patch
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_go_app_audit_proto protoreflect.FileDescriptor

const file_go_app_audit_proto_rawDesc = "" +
	"\n" +
	"\x12go_app/audit.proto\x12\x06go_app\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\"\xf1\x02\n" +
	"\x05Audit\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12#\n" +
	"\ttenant_id\x18\x02 \x01(\fB\x06\xea\x82\x16\x02\x10@R\btenantId\x12!\n" +
	"\bactor_id\x18\x03 \x01(\fB\x06\xea\x82\x16\x02\x10@R\aactorId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\fR\atraceId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12#\n" +
	"\tobject_id\x18\x06 \x01(\fB\x06\xea\x82\x16\x02\x10@R\bobjectId\x12\x14\n" +
	"\x05patch\x18\a \x01(\fR\x05patch\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:K\xca\xfc\x15G\x12\x02\x10\x01\x1a\x17\x12\x06object\x1a\r\n" +
	"\tobject_id\x10\x06\x1a(\x12\x05trail\x1a\r\n" +
	"\ttenant_id\x10\x02\x1a\x10\n" +
	"\fdate_created\x10\x0fB!Z\x1agithub.com/lesomnus/go-app\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_go_app_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_go_app_audit_proto_goTypes = []any{
	(*Audit)(nil),                 // 0: go_app.Audit
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_go_app_audit_proto_depIdxs = []int32{
	1, // 0: go_app.Audit.date_created:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_go_app_audit_proto_init() }
func file_go_app_audit_proto_init() {
	if File_go_app_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_audit_proto_rawDesc), len(file_go_app_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_app_audit_proto_goTypes,
		DependencyIndexes: file_go_app_audit_proto_depIdxs,
		MessageInfos:      file_go_app_audit_proto_msgTypes,
	}.Build()
	File_go_app_audit_proto = out.File
	file_go_app_audit_proto_goTypes = nil
	file_go_app_audit_proto_depIdxs = nil
}
