// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/audit_svc.proto

package go_app

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_TenantId    []byte                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ActorId     []byte                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId"`
	xxx_hidden_TraceId     []byte                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId"`
	xxx_hidden_Action      string                 `protobuf:"bytes,5,opt,name=action"`
	xxx_hidden_ObjectId    []byte                 `protobuf:"bytes,6,opt,name=object_id,json=objectId"`
	xxx_hidden_Patch       []byte                 `protobuf:"bytes,7,opt,name=patch"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuditAddRequest) Reset() {
	*x = AuditAddRequest{}
	mi := &file_go_app_audit_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAddRequest) ProtoMessage() {}

func (x *AuditAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *AuditAddRequest) GetTenantId() []byte {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return nil
}

func (x *AuditAddRequest) GetActorId() []byte {
	if x != nil {
		return x.xxx_hidden_ActorId
	}
	return nil
}

func (x *AuditAddRequest) GetTraceId() []byte {
	if x != nil {
		return x.xxx_hidden_TraceId
	}
	return nil
}

func (x *AuditAddRequest) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *AuditAddRequest) GetObjectId() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectId
	}
	return nil
}

func (x *AuditAddRequest) GetPatch() []byte {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *AuditAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *AuditAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *AuditAddRequest) SetTenantId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TenantId = v
}

func (x *AuditAddRequest) SetActorId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ActorId = v
}

func (x *AuditAddRequest) SetTraceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TraceId = v
}

func (x *AuditAddRequest) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *AuditAddRequest) SetObjectId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectId = v
}

func (x *AuditAddRequest) SetPatch(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Patch = v
}

func (x *AuditAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *AuditAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuditAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *AuditAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AuditAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type AuditAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	TenantId    []byte
	ActorId     []byte
	TraceId     []byte
	Action      string
	ObjectId    []byte
	Patch       []byte
	DateCreated *timestamppb.Timestamp
}

func (b0 AuditAddRequest_builder) Build() *AuditAddRequest {
	m0 := &AuditAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_ActorId = b.ActorId
	x.xxx_hidden_TraceId = b.TraceId
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_ObjectId = b.ObjectId
	x.xxx_hidden_Patch = b.Patch
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type AuditGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *AuditRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *AuditSelect           `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditGetRequest) Reset() {
	*x = AuditGetRequest{}
	mi := &file_go_app_audit_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditGetRequest) ProtoMessage() {}

func (x *AuditGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditGetRequest) GetRef() *AuditRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AuditGetRequest) GetSelect() *AuditSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *AuditGetRequest) SetRef(v *AuditRef) {
	x.xxx_hidden_Ref = v
}

func (x *AuditGetRequest) SetSelect(v *AuditSelect) {
	x.xxx_hidden_Select = v
}

func (x *AuditGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AuditGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *AuditGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AuditGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type AuditGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *AuditRef
	Select *AuditSelect
}

func (b0 AuditGetRequest_builder) Build() *AuditGetRequest {
	m0 := &AuditGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type AuditRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isAuditRef_Key         `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditRef) Reset() {
	*x = AuditRef{}
	mi := &file_go_app_audit_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRef) ProtoMessage() {}

func (x *AuditRef) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*auditRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *AuditRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &auditRef_Id{v}
}

func (x *AuditRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *AuditRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*auditRef_Id)
	return ok
}

func (x *AuditRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *AuditRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*auditRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const AuditRef_Key_not_set_case case_AuditRef_Key = 0
const AuditRef_Id_case case_AuditRef_Key = 1

func (x *AuditRef) WhichKey() case_AuditRef_Key {
	if x == nil {
		return AuditRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *auditRef_Id:
		return AuditRef_Id_case
	default:
		return AuditRef_Key_not_set_case
	}
}

type AuditRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id []byte
	// -- end of xxx_hidden_Key
}

func (b0 AuditRef_builder) Build() *AuditRef {
	m0 := &AuditRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &auditRef_Id{b.Id}
	}
	return m0
}

type case_AuditRef_Key protoreflect.FieldNumber

func (x case_AuditRef_Key) String() string {
	md := file_go_app_audit_svc_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAuditRef_Key interface {
	isAuditRef_Key()
}

type auditRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*auditRef_Id) isAuditRef_Key() {}

type AuditSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_TenantId    bool                   `protobuf:"varint,2,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ActorId     bool                   `protobuf:"varint,3,opt,name=actor_id,json=actorId"`
	xxx_hidden_TraceId     bool                   `protobuf:"varint,4,opt,name=trace_id,json=traceId"`
	xxx_hidden_Action      bool                   `protobuf:"varint,5,opt,name=action"`
	xxx_hidden_ObjectId    bool                   `protobuf:"varint,6,opt,name=object_id,json=objectId"`
	xxx_hidden_Patch       bool                   `protobuf:"varint,7,opt,name=patch"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuditSelect) Reset() {
	*x = AuditSelect{}
	mi := &file_go_app_audit_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditSelect) ProtoMessage() {}

func (x *AuditSelect) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *AuditSelect) GetTenantId() bool {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return false
}

func (x *AuditSelect) GetActorId() bool {
	if x != nil {
		return x.xxx_hidden_ActorId
	}
	return false
}

func (x *AuditSelect) GetTraceId() bool {
	if x != nil {
		return x.xxx_hidden_TraceId
	}
	return false
}

func (x *AuditSelect) GetAction() bool {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return false
}

func (x *AuditSelect) GetObjectId() bool {
	if x != nil {
		return x.xxx_hidden_ObjectId
	}
	return false
}

func (x *AuditSelect) GetPatch() bool {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return false
}

func (x *AuditSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *AuditSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *AuditSelect) SetTenantId(v bool) {
	x.xxx_hidden_TenantId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *AuditSelect) SetActorId(v bool) {
	x.xxx_hidden_ActorId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *AuditSelect) SetTraceId(v bool) {
	x.xxx_hidden_TraceId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *AuditSelect) SetAction(v bool) {
	x.xxx_hidden_Action = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *AuditSelect) SetObjectId(v bool) {
	x.xxx_hidden_ObjectId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *AuditSelect) SetPatch(v bool) {
	x.xxx_hidden_Patch = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *AuditSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *AuditSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuditSelect) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuditSelect) HasActorId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuditSelect) HasTraceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AuditSelect) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AuditSelect) HasObjectId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AuditSelect) HasPatch() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AuditSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AuditSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *AuditSelect) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TenantId = false
}

func (x *AuditSelect) ClearActorId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ActorId = false
}

func (x *AuditSelect) ClearTraceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TraceId = false
}

func (x *AuditSelect) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Action = false
}

func (x *AuditSelect) ClearObjectId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ObjectId = false
}

func (x *AuditSelect) ClearPatch() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Patch = false
}

func (x *AuditSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateCreated = false
}

type AuditSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	TenantId    *bool
	ActorId     *bool
	TraceId     *bool
	Action      *bool
	ObjectId    *bool
	Patch       *bool
	DateCreated *bool
}

func (b0 AuditSelect_builder) Build() *AuditSelect {
	m0 := &AuditSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_All = *b.All
	}
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_TenantId = *b.TenantId
	}
	if b.ActorId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_ActorId = *b.ActorId
	}
	if b.TraceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_TraceId = *b.TraceId
	}
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Action = *b.Action
	}
	if b.ObjectId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_ObjectId = *b.ObjectId
	}
	if b.Patch != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Patch = *b.Patch
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type AuditPatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *AuditRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_TenantId    []byte                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ActorId     []byte                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId"`
	xxx_hidden_TraceId     []byte                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId"`
	xxx_hidden_Action      *string                `protobuf:"bytes,10,opt,name=action"`
	xxx_hidden_ObjectId    []byte                 `protobuf:"bytes,12,opt,name=object_id,json=objectId"`
	xxx_hidden_Patch       []byte                 `protobuf:"bytes,14,opt,name=patch"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuditPatchRequest) Reset() {
	*x = AuditPatchRequest{}
	mi := &file_go_app_audit_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditPatchRequest) ProtoMessage() {}

func (x *AuditPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditPatchRequest) GetRef() *AuditRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AuditPatchRequest) GetTenantId() []byte {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return nil
}

func (x *AuditPatchRequest) GetActorId() []byte {
	if x != nil {
		return x.xxx_hidden_ActorId
	}
	return nil
}

func (x *AuditPatchRequest) GetTraceId() []byte {
	if x != nil {
		return x.xxx_hidden_TraceId
	}
	return nil
}

func (x *AuditPatchRequest) GetAction() string {
	if x != nil {
		if x.xxx_hidden_Action != nil {
			return *x.xxx_hidden_Action
		}
		return ""
	}
	return ""
}

func (x *AuditPatchRequest) GetObjectId() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectId
	}
	return nil
}

func (x *AuditPatchRequest) GetPatch() []byte {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *AuditPatchRequest) SetRef(v *AuditRef) {
	x.xxx_hidden_Ref = v
}

func (x *AuditPatchRequest) SetTenantId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TenantId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *AuditPatchRequest) SetActorId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ActorId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *AuditPatchRequest) SetTraceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TraceId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *AuditPatchRequest) SetAction(v string) {
	x.xxx_hidden_Action = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *AuditPatchRequest) SetObjectId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *AuditPatchRequest) SetPatch(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Patch = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *AuditPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AuditPatchRequest) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuditPatchRequest) HasActorId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuditPatchRequest) HasTraceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AuditPatchRequest) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AuditPatchRequest) HasObjectId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AuditPatchRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AuditPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AuditPatchRequest) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TenantId = nil
}

func (x *AuditPatchRequest) ClearActorId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ActorId = nil
}

func (x *AuditPatchRequest) ClearTraceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TraceId = nil
}

func (x *AuditPatchRequest) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Action = nil
}

func (x *AuditPatchRequest) ClearObjectId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ObjectId = nil
}

func (x *AuditPatchRequest) ClearPatch() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Patch = nil
}

type AuditPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref      *AuditRef
	TenantId []byte
	ActorId  []byte
	TraceId  []byte
	Action   *string
	ObjectId []byte
	Patch    []byte
}

func (b0 AuditPatchRequest_builder) Build() *AuditPatchRequest {
	m0 := &AuditPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.ActorId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ActorId = b.ActorId
	}
	if b.TraceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_TraceId = b.TraceId
	}
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Action = b.Action
	}
	if b.ObjectId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_ObjectId = b.ObjectId
	}
	if b.Patch != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Patch = b.Patch
	}
	return m0
}

type AuditApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *AuditRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditApplyRequest) Reset() {
	*x = AuditApplyRequest{}
	mi := &file_go_app_audit_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditApplyRequest) ProtoMessage() {}

func (x *AuditApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditApplyRequest) GetRef() *AuditRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AuditApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *AuditApplyRequest) SetRef(v *AuditRef) {
	x.xxx_hidden_Ref = v
}

func (x *AuditApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *AuditApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AuditApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *AuditApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AuditApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type AuditApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *AuditRef
	Patch *patchpb.Patch
}

func (b0 AuditApplyRequest_builder) Build() *AuditApplyRequest {
	m0 := &AuditApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type AuditListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters     *[]*AuditFilter        `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_TenantId    []byte                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuditListRequest) Reset() {
	*x = AuditListRequest{}
	mi := &file_go_app_audit_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditListRequest) ProtoMessage() {}

func (x *AuditListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditListRequest) GetFilters() []*AuditFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *AuditListRequest) GetTenantId() []byte {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return nil
}

func (x *AuditListRequest) SetFilters(v []*AuditFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *AuditListRequest) SetTenantId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TenantId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AuditListRequest) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuditListRequest) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TenantId = nil
}

type AuditListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filters []*AuditFilter
	// Whose trail it is, which narrows the answer before it is cut short rather
	// than after. A wall that removed rows from what came back would be a wall
	// that any Tenant could push another one's trail out of, just by writing
	// enough of its own; see `audit.ListLimit`.
	//
	// It is not the caller's to decide: `server/gate` sets it to their own
	// Tenant, whatever they said, unless they are the one Tenant that is not
	// walled in.
	TenantId []byte
}

func (b0 AuditListRequest_builder) Build() *AuditListRequest {
	m0 := &AuditListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_TenantId = b.TenantId
	}
	return m0
}

type AuditListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Audit              `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditListResponse) Reset() {
	*x = AuditListResponse{}
	mi := &file_go_app_audit_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditListResponse) ProtoMessage() {}

func (x *AuditListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditListResponse) GetItems() []*Audit {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *AuditListResponse) SetItems(v []*Audit) {
	x.xxx_hidden_Items = &v
}

type AuditListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Audit
}

func (b0 AuditListResponse_builder) Build() *AuditListResponse {
	m0 := &AuditListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

// AuditFilter names what a caller is asking the history of.
type AuditFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ObjectId    []byte                 `protobuf:"bytes,1,opt,name=object_id,json=objectId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuditFilter) Reset() {
	*x = AuditFilter{}
	mi := &file_go_app_audit_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditFilter) ProtoMessage() {}

func (x *AuditFilter) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_audit_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditFilter) GetObjectId() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectId
	}
	return nil
}

func (x *AuditFilter) SetObjectId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AuditFilter) HasObjectId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuditFilter) ClearObjectId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ObjectId = nil
}

type AuditFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ObjectId []byte
}

func (b0 AuditFilter_builder) Build() *AuditFilter {
	m0 := &AuditFilter{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ObjectId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ObjectId = b.ObjectId
	}
	return m0
}

var File_go_app_audit_svc_proto protoreflect.FileDescriptor

const file_go_app_audit_svc_proto_rawDesc = "" +
	"\n" +
	"\x16go_app/audit_svc.proto\x12\x06go_app\x1a\x12go_app/audit.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\"\xa8\x02\n" +
	"\x0fAuditAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\"\n" +
	"\ttenant_id\x18\x02 \x01(\fB\x05\xaa\x01\x02\b\x02R\btenantId\x12 \n" +
	"\bactor_id\x18\x03 \x01(\fB\x05\xaa\x01\x02\b\x02R\aactorId\x12 \n" +
	"\btrace_id\x18\x04 \x01(\fB\x05\xaa\x01\x02\b\x02R\atraceId\x12\x1d\n" +
	"\x06action\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x06action\x12\"\n" +
	"\tobject_id\x18\x06 \x01(\fB\x05\xaa\x01\x02\b\x02R\bobjectId\x12\x1b\n" +
	"\x05patch\x18\a \x01(\fB\x05\xaa\x01\x02\b\x02R\x05patch\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\"b\n" +
	"\x0fAuditGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.go_app.AuditRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.go_app.AuditSelectR\x06select\"#\n" +
	"\bAuditRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02idB\x05\n" +
	"\x03key\"\xe0\x01\n" +
	"\vAuditSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\bR\btenantId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\bR\aactorId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\bR\atraceId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\bR\x06action\x12\x1b\n" +
	"\tobject_id\x18\x06 \x01(\bR\bobjectId\x12\x14\n" +
	"\x05patch\x18\a \x01(\bR\x05patch\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\xd5\x01\n" +
	"\x11AuditPatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.go_app.AuditRefR\x03ref\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\fR\btenantId\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\fR\aactorId\x12\x19\n" +
	"\btrace_id\x18\b \x01(\fR\atraceId\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\tR\x06action\x12\x1b\n" +
	"\tobject_id\x18\f \x01(\fR\bobjectId\x12\x14\n" +
	"\x05patch\x18\x0e \x01(\fR\x05patch\"[\n" +
	"\x11AuditApplyRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.go_app.AuditRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"^\n" +
	"\x10AuditListRequest\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.go_app.AuditFilterR\afilters\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\fR\btenantId\"8\n" +
	"\x11AuditListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.go_app.AuditR\x05items\"*\n" +
	"\vAuditFilter\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\fR\bobjectId2\xc2\x02\n" +
	"\fAuditService\x12-\n" +
	"\x03Add\x12\x17.go_app.AuditAddRequest\x1a\r.go_app.Audit\x12-\n" +
	"\x03Get\x12\x17.go_app.AuditGetRequest\x1a\r.go_app.Audit\x121\n" +
	"\x05Patch\x12\x19.go_app.AuditPatchRequest\x1a\r.go_app.Audit\x121\n" +
	"\x05Apply\x12\x19.go_app.AuditApplyRequest\x1a\r.go_app.Audit\x121\n" +
	"\x05Erase\x12\x10.go_app.AuditRef\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04List\x12\x18.go_app.AuditListRequest\x1a\x19.go_app.AuditListResponseB\x1cZ\x1agithub.com/lesomnus/go-appb\beditionsp\xe8\a"

var file_go_app_audit_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_go_app_audit_svc_proto_goTypes = []any{
	(*AuditAddRequest)(nil),       // 0: go_app.AuditAddRequest
	(*AuditGetRequest)(nil),       // 1: go_app.AuditGetRequest
	(*AuditRef)(nil),              // 2: go_app.AuditRef
	(*AuditSelect)(nil),           // 3: go_app.AuditSelect
	(*AuditPatchRequest)(nil),     // 4: go_app.AuditPatchRequest
	(*AuditApplyRequest)(nil),     // 5: go_app.AuditApplyRequest
	(*AuditListRequest)(nil),      // 6: go_app.AuditListRequest
	(*AuditListResponse)(nil),     // 7: go_app.AuditListResponse
	(*AuditFilter)(nil),           // 8: go_app.AuditFilter
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*patchpb.Patch)(nil),         // 10: patch.Patch
	(*Audit)(nil),                 // 11: go_app.Audit
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_go_app_audit_svc_proto_depIdxs = []int32{
	9,  // 0: go_app.AuditAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 1: go_app.AuditGetRequest.ref:type_name -> go_app.AuditRef
	3,  // 2: go_app.AuditGetRequest.select:type_name -> go_app.AuditSelect
	2,  // 3: go_app.AuditPatchRequest.ref:type_name -> go_app.AuditRef
	2,  // 4: go_app.AuditApplyRequest.ref:type_name -> go_app.AuditRef
	10, // 5: go_app.AuditApplyRequest.patch:type_name -> patch.Patch
	8,  // 6: go_app.AuditListRequest.filters:type_name -> go_app.AuditFilter
	11, // 7: go_app.AuditListResponse.items:type_name -> go_app.Audit
	0,  // 8: go_app.AuditService.Add:input_type -> go_app.AuditAddRequest
	1,  // 9: go_app.AuditService.Get:input_type -> go_app.AuditGetRequest
	4,  // 10: go_app.AuditService.Patch:input_type -> go_app.AuditPatchRequest
	5,  // 11: go_app.AuditService.Apply:input_type -> go_app.AuditApplyRequest
	2,  // 12: go_app.AuditService.Erase:input_type -> go_app.AuditRef
	6,  // 13: go_app.AuditService.List:input_type -> go_app.AuditListRequest
	11, // 14: go_app.AuditService.Add:output_type -> go_app.Audit
	11, // 15: go_app.AuditService.Get:output_type -> go_app.Audit
	11, // 16: go_app.AuditService.Patch:output_type -> go_app.Audit
	11, // 17: go_app.AuditService.Apply:output_type -> go_app.Audit
	12, // 18: go_app.AuditService.Erase:output_type -> google.protobuf.Empty
	7,  // 19: go_app.AuditService.List:output_type -> go_app.AuditListResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_go_app_audit_svc_proto_init() }
func file_go_app_audit_svc_proto_init() {
	if File_go_app_audit_svc_proto != nil {
		return
	}
	file_go_app_audit_proto_init()
	file_go_app_audit_svc_proto_msgTypes[2].OneofWrappers = []any{
		(*auditRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_audit_svc_proto_rawDesc), len(file_go_app_audit_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_app_audit_svc_proto_goTypes,
		DependencyIndexes: file_go_app_audit_svc_proto_depIdxs,
		MessageInfos:      file_go_app_audit_svc_proto_msgTypes,
	}.Build()
	File_go_app_audit_svc_proto = out.File
	file_go_app_audit_svc_proto_goTypes = nil
	file_go_app_audit_svc_proto_depIdxs = nil
}
