// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/coffee_svc.proto

package go_app

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoffeeAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Roaster     *RoasterRef            `protobuf:"bytes,2,opt,name=roaster"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,3,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,4,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,5,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,6,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoffeeAddRequest) Reset() {
	*x = CoffeeAddRequest{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeAddRequest) ProtoMessage() {}

func (x *CoffeeAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *CoffeeAddRequest) GetRoaster() *RoasterRef {
	if x != nil {
		return x.xxx_hidden_Roaster
	}
	return nil
}

func (x *CoffeeAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *CoffeeAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *CoffeeAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *CoffeeAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *CoffeeAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *CoffeeAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *CoffeeAddRequest) SetRoaster(v *RoasterRef) {
	x.xxx_hidden_Roaster = v
}

func (x *CoffeeAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *CoffeeAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *CoffeeAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *CoffeeAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *CoffeeAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *CoffeeAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CoffeeAddRequest) HasRoaster() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Roaster != nil
}

func (x *CoffeeAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *CoffeeAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CoffeeAddRequest) ClearRoaster() {
	x.xxx_hidden_Roaster = nil
}

func (x *CoffeeAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type CoffeeAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Roaster     *RoasterRef
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	DateCreated *timestamppb.Timestamp
}

func (b0 CoffeeAddRequest_builder) Build() *CoffeeAddRequest {
	m0 := &CoffeeAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Roaster = b.Roaster
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type CoffeeGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *CoffeeRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *CoffeeSelect          `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CoffeeGetRequest) Reset() {
	*x = CoffeeGetRequest{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeGetRequest) ProtoMessage() {}

func (x *CoffeeGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeGetRequest) GetRef() *CoffeeRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *CoffeeGetRequest) GetSelect() *CoffeeSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *CoffeeGetRequest) SetRef(v *CoffeeRef) {
	x.xxx_hidden_Ref = v
}

func (x *CoffeeGetRequest) SetSelect(v *CoffeeSelect) {
	x.xxx_hidden_Select = v
}

func (x *CoffeeGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *CoffeeGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *CoffeeGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *CoffeeGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type CoffeeGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *CoffeeRef
	Select *CoffeeSelect
}

func (b0 CoffeeGetRequest_builder) Build() *CoffeeGetRequest {
	m0 := &CoffeeGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type CoffeeRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isCoffeeRef_Key        `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CoffeeRef) Reset() {
	*x = CoffeeRef{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeRef) ProtoMessage() {}

func (x *CoffeeRef) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*coffeeRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *CoffeeRef) GetSlug() *CoffeeRefBySlug {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*coffeeRef_Slug); ok {
			return x.Slug
		}
	}
	return nil
}

func (x *CoffeeRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &coffeeRef_Id{v}
}

func (x *CoffeeRef) SetSlug(v *CoffeeRefBySlug) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &coffeeRef_Slug{v}
}

func (x *CoffeeRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *CoffeeRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*coffeeRef_Id)
	return ok
}

func (x *CoffeeRef) HasSlug() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*coffeeRef_Slug)
	return ok
}

func (x *CoffeeRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *CoffeeRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*coffeeRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *CoffeeRef) ClearSlug() {
	if _, ok := x.xxx_hidden_Key.(*coffeeRef_Slug); ok {
		x.xxx_hidden_Key = nil
	}
}

const CoffeeRef_Key_not_set_case case_CoffeeRef_Key = 0
const CoffeeRef_Id_case case_CoffeeRef_Key = 1
const CoffeeRef_Slug_case case_CoffeeRef_Key = 3

func (x *CoffeeRef) WhichKey() case_CoffeeRef_Key {
	if x == nil {
		return CoffeeRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *coffeeRef_Id:
		return CoffeeRef_Id_case
	case *coffeeRef_Slug:
		return CoffeeRef_Slug_case
	default:
		return CoffeeRef_Key_not_set_case
	}
}

type CoffeeRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id   []byte
	Slug *CoffeeRefBySlug
	// -- end of xxx_hidden_Key
}

func (b0 CoffeeRef_builder) Build() *CoffeeRef {
	m0 := &CoffeeRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &coffeeRef_Id{b.Id}
	}
	if b.Slug != nil {
		x.xxx_hidden_Key = &coffeeRef_Slug{b.Slug}
	}
	return m0
}

type case_CoffeeRef_Key protoreflect.FieldNumber

func (x case_CoffeeRef_Key) String() string {
	md := file_go_app_coffee_svc_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isCoffeeRef_Key interface {
	isCoffeeRef_Key()
}

type coffeeRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type coffeeRef_Slug struct {
	Slug *CoffeeRefBySlug `protobuf:"bytes,3,opt,name=slug,oneof"`
}

func (*coffeeRef_Id) isCoffeeRef_Key() {}

func (*coffeeRef_Slug) isCoffeeRef_Key() {}

type CoffeeRefBySlug struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,3,opt,name=alias"`
	xxx_hidden_Roaster     *RoasterRef            `protobuf:"bytes,2,opt,name=roaster"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoffeeRefBySlug) Reset() {
	*x = CoffeeRefBySlug{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeRefBySlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeRefBySlug) ProtoMessage() {}

func (x *CoffeeRefBySlug) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeRefBySlug) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *CoffeeRefBySlug) GetRoaster() *RoasterRef {
	if x != nil {
		return x.xxx_hidden_Roaster
	}
	return nil
}

func (x *CoffeeRefBySlug) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CoffeeRefBySlug) SetRoaster(v *RoasterRef) {
	x.xxx_hidden_Roaster = v
}

func (x *CoffeeRefBySlug) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CoffeeRefBySlug) HasRoaster() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Roaster != nil
}

func (x *CoffeeRefBySlug) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *CoffeeRefBySlug) ClearRoaster() {
	x.xxx_hidden_Roaster = nil
}

type CoffeeRefBySlug_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias   *string
	Roaster *RoasterRef
}

func (b0 CoffeeRefBySlug_builder) Build() *CoffeeRefBySlug {
	m0 := &CoffeeRefBySlug{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_Roaster = b.Roaster
	return m0
}

type CoffeeSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Roaster     *RoasterSelect         `protobuf:"bytes,2,opt,name=roaster"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,3,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,4,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,5,opt,name=desc"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,6,opt,name=labels"`
	xxx_hidden_DateErased  bool                   `protobuf:"varint,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoffeeSelect) Reset() {
	*x = CoffeeSelect{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeSelect) ProtoMessage() {}

func (x *CoffeeSelect) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *CoffeeSelect) GetRoaster() *RoasterSelect {
	if x != nil {
		return x.xxx_hidden_Roaster
	}
	return nil
}

func (x *CoffeeSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *CoffeeSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *CoffeeSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *CoffeeSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *CoffeeSelect) GetDateErased() bool {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return false
}

func (x *CoffeeSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *CoffeeSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *CoffeeSelect) SetRoaster(v *RoasterSelect) {
	x.xxx_hidden_Roaster = v
}

func (x *CoffeeSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *CoffeeSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *CoffeeSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *CoffeeSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *CoffeeSelect) SetDateErased(v bool) {
	x.xxx_hidden_DateErased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *CoffeeSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *CoffeeSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CoffeeSelect) HasRoaster() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Roaster != nil
}

func (x *CoffeeSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CoffeeSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CoffeeSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CoffeeSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CoffeeSelect) HasDateErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *CoffeeSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *CoffeeSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *CoffeeSelect) ClearRoaster() {
	x.xxx_hidden_Roaster = nil
}

func (x *CoffeeSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = false
}

func (x *CoffeeSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = false
}

func (x *CoffeeSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Desc = false
}

func (x *CoffeeSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Labels = false
}

func (x *CoffeeSelect) ClearDateErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateErased = false
}

func (x *CoffeeSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateCreated = false
}

type CoffeeSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Roaster     *RoasterSelect
	Alias       *bool
	Name        *bool
	Desc        *bool
	Labels      *bool
	DateErased  *bool
	DateCreated *bool
}

func (b0 CoffeeSelect_builder) Build() *CoffeeSelect {
	m0 := &CoffeeSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Roaster = b.Roaster
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.DateErased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_DateErased = *b.DateErased
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type CoffeePatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *CoffeeRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,6,opt,name=alias"`
	xxx_hidden_Name        *string                `protobuf:"bytes,8,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,10,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,12,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoffeePatchRequest) Reset() {
	*x = CoffeePatchRequest{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeePatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeePatchRequest) ProtoMessage() {}

func (x *CoffeePatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeePatchRequest) GetRef() *CoffeeRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *CoffeePatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *CoffeePatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CoffeePatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *CoffeePatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *CoffeePatchRequest) SetRef(v *CoffeeRef) {
	x.xxx_hidden_Ref = v
}

func (x *CoffeePatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CoffeePatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CoffeePatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CoffeePatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *CoffeePatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *CoffeePatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CoffeePatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CoffeePatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CoffeePatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *CoffeePatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *CoffeePatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *CoffeePatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

type CoffeePatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *CoffeeRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
}

func (b0 CoffeePatchRequest_builder) Build() *CoffeePatchRequest {
	m0 := &CoffeePatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type CoffeeApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *CoffeeRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoffeeApplyRequest) Reset() {
	*x = CoffeeApplyRequest{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeApplyRequest) ProtoMessage() {}

func (x *CoffeeApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeApplyRequest) GetRef() *CoffeeRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *CoffeeApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *CoffeeApplyRequest) SetRef(v *CoffeeRef) {
	x.xxx_hidden_Ref = v
}

func (x *CoffeeApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *CoffeeApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *CoffeeApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *CoffeeApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *CoffeeApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type CoffeeApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *CoffeeRef
	Patch *patchpb.Patch
}

func (b0 CoffeeApplyRequest_builder) Build() *CoffeeApplyRequest {
	m0 := &CoffeeApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type CoffeeListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters     *[]*CoffeeFilter       `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size        int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After       *string                `protobuf:"bytes,3,opt,name=after"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoffeeListRequest) Reset() {
	*x = CoffeeListRequest{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeListRequest) ProtoMessage() {}

func (x *CoffeeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeListRequest) GetFilters() []*CoffeeFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *CoffeeListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *CoffeeListRequest) GetAfter() string {
	if x != nil {
		if x.xxx_hidden_After != nil {
			return *x.xxx_hidden_After
		}
		return ""
	}
	return ""
}

func (x *CoffeeListRequest) SetFilters(v []*CoffeeFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *CoffeeListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CoffeeListRequest) SetAfter(v string) {
	x.xxx_hidden_After = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CoffeeListRequest) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CoffeeListRequest) HasAfter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CoffeeListRequest) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *CoffeeListRequest) ClearAfter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_After = nil
}

type CoffeeListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is: each one is a predicate in the same query, and
	// a request may carry as many as it likes. The bound is in `core.List`, where
	// a reader of it can see what it costs.
	Filters []*CoffeeFilter
	// How many to answer with. Nothing said is `core.PageSize`, and more than
	// `core.PageLimit` is `core.PageLimit` -- a caller asking for more than there
	// is meant no harm, so it is not an error, and it is not the whole table
	// either.
	Size *int32
	// Where to carry on from: the `next` of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a Coffee
	// added while a caller is reading does not shift the page under them.
	After *string
}

func (b0 CoffeeListRequest_builder) Build() *CoffeeListRequest {
	m0 := &CoffeeListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Size = *b.Size
	}
	if b.After != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_After = b.After
	}
	return m0
}

type CoffeeListResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items       *[]*Coffee             `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next        *string                `protobuf:"bytes,2,opt,name=next"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoffeeListResponse) Reset() {
	*x = CoffeeListResponse{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeListResponse) ProtoMessage() {}

func (x *CoffeeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeListResponse) GetItems() []*Coffee {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *CoffeeListResponse) GetNext() string {
	if x != nil {
		if x.xxx_hidden_Next != nil {
			return *x.xxx_hidden_Next
		}
		return ""
	}
	return ""
}

func (x *CoffeeListResponse) SetItems(v []*Coffee) {
	x.xxx_hidden_Items = &v
}

func (x *CoffeeListResponse) SetNext(v string) {
	x.xxx_hidden_Next = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CoffeeListResponse) HasNext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CoffeeListResponse) ClearNext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Next = nil
}

type CoffeeListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Coffee
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing this server can only know by having
	// looked.
	Next *string
}

func (b0 CoffeeListResponse_builder) Build() *CoffeeListResponse {
	m0 := &CoffeeListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.Next != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Next = b.Next
	}
	return m0
}

type CoffeeFilter struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref *CoffeeRef             `protobuf:"bytes,1,opt,name=ref"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CoffeeFilter) Reset() {
	*x = CoffeeFilter{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeFilter) ProtoMessage() {}

func (x *CoffeeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeFilter) GetRef() *CoffeeRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *CoffeeFilter) SetRef(v *CoffeeRef) {
	x.xxx_hidden_Ref = v
}

func (x *CoffeeFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *CoffeeFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

type CoffeeFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *CoffeeRef
}

func (b0 CoffeeFilter_builder) Build() *CoffeeFilter {
	m0 := &CoffeeFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	return m0
}

type CoffeeWatchRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*CoffeeFilter       `protobuf:"bytes,1,rep,name=filters"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CoffeeWatchRequest) Reset() {
	*x = CoffeeWatchRequest{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeWatchRequest) ProtoMessage() {}

func (x *CoffeeWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeWatchRequest) GetFilters() []*CoffeeFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *CoffeeWatchRequest) SetFilters(v []*CoffeeFilter) {
	x.xxx_hidden_Filters = &v
}

type CoffeeWatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which Coffees to watch, in the same words `List` takes them: what is
	// watched is what that list would answer with, now and afterwards.
	//
	// Bounded the way `CoffeeListRequest.filters` is, and for a heavier reason. A
	// list runs its filters once; a watch runs them again for every write that
	// touches a Coffee, for as long as the stream is open.
	Filters []*CoffeeFilter
}

func (b0 CoffeeWatchRequest_builder) Build() *CoffeeWatchRequest {
	m0 := &CoffeeWatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	return m0
}

type CoffeeWatchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*CoffeeWatchItem    `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoffeeWatchResponse) Reset() {
	*x = CoffeeWatchResponse{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeWatchResponse) ProtoMessage() {}

func (x *CoffeeWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeWatchResponse) GetItems() []*CoffeeWatchItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *CoffeeWatchResponse) SetItems(v []*CoffeeWatchItem) {
	x.xxx_hidden_Items = &v
}

type CoffeeWatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// What changed, or -- in the first message -- everything that matches.
	Items []*CoffeeWatchItem
}

func (b0 CoffeeWatchResponse_builder) Build() *CoffeeWatchResponse {
	m0 := &CoffeeWatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type CoffeeWatchItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       *Coffee                `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Action      *string                `protobuf:"bytes,3,opt,name=action"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CoffeeWatchItem) Reset() {
	*x = CoffeeWatchItem{}
	mi := &file_go_app_coffee_svc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeWatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeWatchItem) ProtoMessage() {}

func (x *CoffeeWatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_svc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CoffeeWatchItem) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *CoffeeWatchItem) GetValue() *Coffee {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *CoffeeWatchItem) GetAction() string {
	if x != nil {
		if x.xxx_hidden_Action != nil {
			return *x.xxx_hidden_Action
		}
		return ""
	}
	return ""
}

func (x *CoffeeWatchItem) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CoffeeWatchItem) SetValue(v *Coffee) {
	x.xxx_hidden_Value = v
}

func (x *CoffeeWatchItem) SetAction(v string) {
	x.xxx_hidden_Action = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CoffeeWatchItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CoffeeWatchItem) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *CoffeeWatchItem) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CoffeeWatchItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CoffeeWatchItem) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *CoffeeWatchItem) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Action = nil
}

type CoffeeWatchItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which Coffee. Always said, since one that is gone still has to be named.
	Id []byte
	// The Coffee as it is now, and **absent when it is no longer one this caller
	// may see**: erased, or moved out of the filters this stream named.
	//
	// Absence is the whole of how a removal is said. There is no flag for it, and
	// it is only ever said about a Coffee this stream has already carried -- one
	// that never matched is not news.
	Value *Coffee
	// The RPC that changed it, by the name gRPC knows it by:
	// "/go_app.CoffeeService/Add". It is what the caller of *that* RPC asked for
	// and not the write it became, so an RPC written by hand is here under its
	// own name and a client reads what it means from that RPC's documentation.
	//
	// Empty in the first message, which is not something anybody asked for -- it
	// is what is already there.
	Action *string
}

func (b0 CoffeeWatchItem_builder) Build() *CoffeeWatchItem {
	m0 := &CoffeeWatchItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Value = b.Value
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Action = b.Action
	}
	return m0
}

var File_go_app_coffee_svc_proto protoreflect.FileDescriptor

const file_go_app_coffee_svc_proto_rawDesc = "" +
	"\n" +
	"\x17go_app/coffee_svc.proto\x12\x06go_app\x1a\x13go_app/coffee.proto\x1a\x18go_app/roaster_svc.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\"\xdb\x02\n" +
	"\x10CoffeeAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12,\n" +
	"\aroaster\x18\x02 \x01(\v2\x12.go_app.RoasterRefR\aroaster\x12\x1b\n" +
	"\x05alias\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x12<\n" +
	"\x06labels\x18\x06 \x03(\v2$.go_app.CoffeeAddRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x10CoffeeGetRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.CoffeeRefR\x03ref\x12,\n" +
	"\x06select\x18\x02 \x01(\v2\x14.go_app.CoffeeSelectR\x06select\"S\n" +
	"\tCoffeeRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12-\n" +
	"\x04slug\x18\x03 \x01(\v2\x17.go_app.CoffeeRefBySlugH\x00R\x04slugB\x05\n" +
	"\x03key\"U\n" +
	"\x0fCoffeeRefBySlug\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12,\n" +
	"\aroaster\x18\x02 \x01(\v2\x12.go_app.RoasterRefR\aroaster\"\xeb\x01\n" +
	"\fCoffeeSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12/\n" +
	"\aroaster\x18\x02 \x01(\v2\x15.go_app.RoasterSelectR\aroaster\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x04 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\x06 \x01(\bR\x06labels\x12\x1f\n" +
	"\vdate_erased\x18\x0e \x01(\bR\n" +
	"dateErased\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\xf2\x01\n" +
	"\x12CoffeePatchRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.CoffeeRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\x06 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\n" +
	" \x01(\tR\x04desc\x12>\n" +
	"\x06labels\x18\f \x03(\v2&.go_app.CoffeePatchRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x12CoffeeApplyRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.CoffeeRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"m\n" +
	"\x11CoffeeListRequest\x12.\n" +
	"\afilters\x18\x01 \x03(\v2\x14.go_app.CoffeeFilterR\afilters\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\"N\n" +
	"\x12CoffeeListResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.go_app.CoffeeR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"3\n" +
	"\fCoffeeFilter\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.CoffeeRefR\x03ref\"D\n" +
	"\x12CoffeeWatchRequest\x12.\n" +
	"\afilters\x18\x01 \x03(\v2\x14.go_app.CoffeeFilterR\afilters\"D\n" +
	"\x13CoffeeWatchResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.go_app.CoffeeWatchItemR\x05items\"_\n" +
	"\x0fCoffeeWatchItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.go_app.CoffeeR\x05value\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action2\x92\x03\n" +
	"\rCoffeeService\x12/\n" +
	"\x03Add\x12\x18.go_app.CoffeeAddRequest\x1a\x0e.go_app.Coffee\x12/\n" +
	"\x03Get\x12\x18.go_app.CoffeeGetRequest\x1a\x0e.go_app.Coffee\x123\n" +
	"\x05Patch\x12\x1a.go_app.CoffeePatchRequest\x1a\x0e.go_app.Coffee\x123\n" +
	"\x05Apply\x12\x1a.go_app.CoffeeApplyRequest\x1a\x0e.go_app.Coffee\x122\n" +
	"\x05Erase\x12\x11.go_app.CoffeeRef\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x04List\x12\x19.go_app.CoffeeListRequest\x1a\x1a.go_app.CoffeeListResponse\x12B\n" +
	"\x05Watch\x12\x1a.go_app.CoffeeWatchRequest\x1a\x1b.go_app.CoffeeWatchResponse0\x01B\x1cZ\x1agithub.com/lesomnus/go-appb\beditionsp\xe8\a"

var file_go_app_coffee_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_go_app_coffee_svc_proto_goTypes = []any{
	(*CoffeeAddRequest)(nil),      // 0: go_app.CoffeeAddRequest
	(*CoffeeGetRequest)(nil),      // 1: go_app.CoffeeGetRequest
	(*CoffeeRef)(nil),             // 2: go_app.CoffeeRef
	(*CoffeeRefBySlug)(nil),       // 3: go_app.CoffeeRefBySlug
	(*CoffeeSelect)(nil),          // 4: go_app.CoffeeSelect
	(*CoffeePatchRequest)(nil),    // 5: go_app.CoffeePatchRequest
	(*CoffeeApplyRequest)(nil),    // 6: go_app.CoffeeApplyRequest
	(*CoffeeListRequest)(nil),     // 7: go_app.CoffeeListRequest
	(*CoffeeListResponse)(nil),    // 8: go_app.CoffeeListResponse
	(*CoffeeFilter)(nil),          // 9: go_app.CoffeeFilter
	(*CoffeeWatchRequest)(nil),    // 10: go_app.CoffeeWatchRequest
	(*CoffeeWatchResponse)(nil),   // 11: go_app.CoffeeWatchResponse
	(*CoffeeWatchItem)(nil),       // 12: go_app.CoffeeWatchItem
	nil,                           // 13: go_app.CoffeeAddRequest.LabelsEntry
	nil,                           // 14: go_app.CoffeePatchRequest.LabelsEntry
	(*RoasterRef)(nil),            // 15: go_app.RoasterRef
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*RoasterSelect)(nil),         // 17: go_app.RoasterSelect
	(*patchpb.Patch)(nil),         // 18: patch.Patch
	(*Coffee)(nil),                // 19: go_app.Coffee
	(*emptypb.Empty)(nil),         // 20: google.protobuf.Empty
}
var file_go_app_coffee_svc_proto_depIdxs = []int32{
	15, // 0: go_app.CoffeeAddRequest.roaster:type_name -> go_app.RoasterRef
	13, // 1: go_app.CoffeeAddRequest.labels:type_name -> go_app.CoffeeAddRequest.LabelsEntry
	16, // 2: go_app.CoffeeAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 3: go_app.CoffeeGetRequest.ref:type_name -> go_app.CoffeeRef
	4,  // 4: go_app.CoffeeGetRequest.select:type_name -> go_app.CoffeeSelect
	3,  // 5: go_app.CoffeeRef.slug:type_name -> go_app.CoffeeRefBySlug
	15, // 6: go_app.CoffeeRefBySlug.roaster:type_name -> go_app.RoasterRef
	17, // 7: go_app.CoffeeSelect.roaster:type_name -> go_app.RoasterSelect
	2,  // 8: go_app.CoffeePatchRequest.ref:type_name -> go_app.CoffeeRef
	14, // 9: go_app.CoffeePatchRequest.labels:type_name -> go_app.CoffeePatchRequest.LabelsEntry
	2,  // 10: go_app.CoffeeApplyRequest.ref:type_name -> go_app.CoffeeRef
	18, // 11: go_app.CoffeeApplyRequest.patch:type_name -> patch.Patch
	9,  // 12: go_app.CoffeeListRequest.filters:type_name -> go_app.CoffeeFilter
	19, // 13: go_app.CoffeeListResponse.items:type_name -> go_app.Coffee
	2,  // 14: go_app.CoffeeFilter.ref:type_name -> go_app.CoffeeRef
	9,  // 15: go_app.CoffeeWatchRequest.filters:type_name -> go_app.CoffeeFilter
	12, // 16: go_app.CoffeeWatchResponse.items:type_name -> go_app.CoffeeWatchItem
	19, // 17: go_app.CoffeeWatchItem.value:type_name -> go_app.Coffee
	0,  // 18: go_app.CoffeeService.Add:input_type -> go_app.CoffeeAddRequest
	1,  // 19: go_app.CoffeeService.Get:input_type -> go_app.CoffeeGetRequest
	5,  // 20: go_app.CoffeeService.Patch:input_type -> go_app.CoffeePatchRequest
	6,  // 21: go_app.CoffeeService.Apply:input_type -> go_app.CoffeeApplyRequest
	2,  // 22: go_app.CoffeeService.Erase:input_type -> go_app.CoffeeRef
	7,  // 23: go_app.CoffeeService.List:input_type -> go_app.CoffeeListRequest
	10, // 24: go_app.CoffeeService.Watch:input_type -> go_app.CoffeeWatchRequest
	19, // 25: go_app.CoffeeService.Add:output_type -> go_app.Coffee
	19, // 26: go_app.CoffeeService.Get:output_type -> go_app.Coffee
	19, // 27: go_app.CoffeeService.Patch:output_type -> go_app.Coffee
	19, // 28: go_app.CoffeeService.Apply:output_type -> go_app.Coffee
	20, // 29: go_app.CoffeeService.Erase:output_type -> google.protobuf.Empty
	8,  // 30: go_app.CoffeeService.List:output_type -> go_app.CoffeeListResponse
	11, // 31: go_app.CoffeeService.Watch:output_type -> go_app.CoffeeWatchResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_go_app_coffee_svc_proto_init() }
func file_go_app_coffee_svc_proto_init() {
	if File_go_app_coffee_svc_proto != nil {
		return
	}
	file_go_app_coffee_proto_init()
	file_go_app_roaster_svc_proto_init()
	file_go_app_coffee_svc_proto_msgTypes[2].OneofWrappers = []any{
		(*coffeeRef_Id)(nil),
		(*coffeeRef_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_coffee_svc_proto_rawDesc), len(file_go_app_coffee_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_app_coffee_svc_proto_goTypes,
		DependencyIndexes: file_go_app_coffee_svc_proto_depIdxs,
		MessageInfos:      file_go_app_coffee_svc_proto_msgTypes,
	}.Build()
	File_go_app_coffee_svc_proto = out.File
	file_go_app_coffee_svc_proto_goTypes = nil
	file_go_app_coffee_svc_proto_depIdxs = nil
}
