// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/coffee.proto

package go_app

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Coffee is what this app is about, and is deliberately a thing rather than a
// person: a template whose one entity is called `User` has already decided that
// the app is about accounts, and most apps are not.
type Coffee struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Roaster     *Roaster               `protobuf:"bytes,2,opt,name=roaster"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,3,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,4,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,5,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,6,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Coffee) Reset() {
	*x = Coffee{}
	mi := &file_go_app_coffee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coffee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coffee) ProtoMessage() {}

func (x *Coffee) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_coffee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Coffee) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Coffee) GetRoaster() *Roaster {
	if x != nil {
		return x.xxx_hidden_Roaster
	}
	return nil
}

func (x *Coffee) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Coffee) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Coffee) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Coffee) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Coffee) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Coffee) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Coffee) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Coffee) SetRoaster(v *Roaster) {
	x.xxx_hidden_Roaster = v
}

func (x *Coffee) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Coffee) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Coffee) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Coffee) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *Coffee) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Coffee) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Coffee) HasRoaster() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Roaster != nil
}

func (x *Coffee) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Coffee) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Coffee) ClearRoaster() {
	x.xxx_hidden_Roaster = nil
}

func (x *Coffee) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Coffee) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Coffee_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// Who roasted it. Immutable, because a Coffee moving from one Roaster to
	// another is not a thing that happens -- and because an immutable edge is
	// what most edges are, and so the one worth showing.
	Roaster *Roaster
	// The name it is known by, unique *within its Roaster*. That is the `slug`
	// index below, and it is the shape almost every name has in an app that has
	// more than one table.
	Alias  string
	Name   string
	Desc   string
	Labels map[string]string
	// When this Coffee was erased, and null for as long as it is here.
	//
	// It is erased softly, and the reason is the identifier. A row that is gone
	// for real leaves its identifier free to be answered by something else one
	// day, and anything that kept one -- a link somebody saved, a row in another
	// system, an event that was published -- would then be pointing at a coffee
	// nobody meant. Stamping keeps the identifier taken for good.
	//
	// What follows is what soft erasure always follows with: an erased Coffee
	// cannot be read and cannot be changed, because every read is narrowed by
	// this column. The `slug` index below covers only the rows that are still
	// here, so the *alias* comes free again -- an identifier is forever and a
	// name is not. That is a choice either way (`includes_erased`), and it is
	// usually the one wanted.
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 Coffee_builder) Build() *Coffee {
	m0 := &Coffee{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Roaster = b.Roaster
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_go_app_coffee_proto protoreflect.FileDescriptor

const file_go_app_coffee_proto_rawDesc = "" +
	"\n" +
	"\x13go_app/coffee.proto\x12\x06go_app\x1a\x14go_app/roaster.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\"\xc1\x03\n" +
	"\x06Coffee\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x121\n" +
	"\aroaster\x18\x02 \x01(\v2\x0f.go_app.RoasterB\x06\xf2\x82\x16\x02@\x01R\aroaster\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x122\n" +
	"\x06labels\x18\x06 \x03(\v2\x1a.go_app.Coffee.LabelsEntryR\x06labels\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:*\xca\xfc\x15&\x12\x02\x10\x01\x1a \x12\x04slug\x1a\t\n" +
	"\x05alias\x10\x03\x1a\v\n" +
	"\aroaster\x10\x020\x01B!Z\x1agithub.com/lesomnus/go-app\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_go_app_coffee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_app_coffee_proto_goTypes = []any{
	(*Coffee)(nil),                // 0: go_app.Coffee
	nil,                           // 1: go_app.Coffee.LabelsEntry
	(*Roaster)(nil),               // 2: go_app.Roaster
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_go_app_coffee_proto_depIdxs = []int32{
	2, // 0: go_app.Coffee.roaster:type_name -> go_app.Roaster
	1, // 1: go_app.Coffee.labels:type_name -> go_app.Coffee.LabelsEntry
	3, // 2: go_app.Coffee.date_erased:type_name -> google.protobuf.Timestamp
	3, // 3: go_app.Coffee.date_created:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_go_app_coffee_proto_init() }
func file_go_app_coffee_proto_init() {
	if File_go_app_coffee_proto != nil {
		return
	}
	file_go_app_roaster_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_coffee_proto_rawDesc), len(file_go_app_coffee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_app_coffee_proto_goTypes,
		DependencyIndexes: file_go_app_coffee_proto_depIdxs,
		MessageInfos:      file_go_app_coffee_proto_msgTypes,
	}.Build()
	File_go_app_coffee_proto = out.File
	file_go_app_coffee_proto_goTypes = nil
	file_go_app_coffee_proto_depIdxs = nil
}
