// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package go_app

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *CoffeeRef) Pick() *CoffeeGetRequest {
	return CoffeeGetRequest_builder{Ref: x}.Build()
}

func (x *Coffee) Ref() *CoffeeRef {
	if v := x.GetId(); len(v) > 0 {
		return CoffeeById(v)
	}
	{
		v1 := x.GetAlias()
		v2 := x.GetRoaster()
		if len(v1) > 0 && v2 != nil {
			return CoffeeBySlug(v1, v2.Ref())
		}
	}

	return nil
}

func (x *Coffee) Pick() *CoffeeGetRequest {
	return x.Ref().Pick()
}

func (x *CoffeeRef) Picks(v *Coffee) bool {
	switch x.WhichKey() {
	case CoffeeRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case CoffeeRef_Slug_case:
		x := x.GetSlug()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetRoaster().Picks(v.GetRoaster()))
	default:
		return false
	}
}

func (x *CoffeeGetRequest) WithSelect(f func(s *CoffeeSelect)) *CoffeeGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&CoffeeSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Coffee) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Coffee) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func CoffeeById(v []byte) *CoffeeRef {
	x := &CoffeeRef{}
	x.SetId(v)
	return x
}

func CoffeeGetById(v []byte) *CoffeeGetRequest {
	return CoffeeGetRequest_builder{Ref: CoffeeById(v)}.Build()
}

func CoffeeBySlug(alias string, roaster *RoasterRef) *CoffeeRef {
	x := &CoffeeRefBySlug{}
	x.SetAlias(alias)
	x.SetRoaster(roaster)
	return CoffeeRef_builder{Slug: x}.Build()
}

func CoffeeGetBySlug(alias string, roaster *RoasterRef) *CoffeeGetRequest {
	return CoffeeGetRequest_builder{Ref: CoffeeBySlug(alias, roaster)}.Build()
}
