// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: go_app/coffee_svc.proto

package go_app

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeeService_Add_FullMethodName   = "/go_app.CoffeeService/Add"
	CoffeeService_Get_FullMethodName   = "/go_app.CoffeeService/Get"
	CoffeeService_Patch_FullMethodName = "/go_app.CoffeeService/Patch"
	CoffeeService_Apply_FullMethodName = "/go_app.CoffeeService/Apply"
	CoffeeService_Erase_FullMethodName = "/go_app.CoffeeService/Erase"
	CoffeeService_List_FullMethodName  = "/go_app.CoffeeService/List"
	CoffeeService_Watch_FullMethodName = "/go_app.CoffeeService/Watch"
)

// CoffeeServiceClient is the client API for CoffeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoffeeServiceClient interface {
	// Add creates a new Coffee
	Add(ctx context.Context, in *CoffeeAddRequest, opts ...grpc.CallOption) (*Coffee, error)
	// Get retrieves a Coffee
	Get(ctx context.Context, in *CoffeeGetRequest, opts ...grpc.CallOption) (*Coffee, error)
	// Patch updates an existing Coffee
	Patch(ctx context.Context, in *CoffeePatchRequest, opts ...grpc.CallOption) (*Coffee, error)
	// Apply applies a patch document to an existing Coffee
	Apply(ctx context.Context, in *CoffeeApplyRequest, opts ...grpc.CallOption) (*Coffee, error)
	// Erase deletes a Coffee
	Erase(ctx context.Context, in *CoffeeRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List the Coffees that match any of the given filters, a page at a time.
	List(ctx context.Context, in *CoffeeListRequest, opts ...grpc.CallOption) (*CoffeeListResponse, error)
	// Watch the Coffees a caller may see, as they are now and as they change.
	//
	// What arrives is state and never a delta, so a client converges rather than
	// replays: it keeps what it was last told about a Coffee and replaces it. An
	// event it did not receive is one it does not need, since the next one about
	// that Coffee carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A Coffee may arrive twice
	// -- once in that first message and once as a change that happened while it
	// was being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *CoffeeWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CoffeeWatchResponse], error)
}

type coffeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeServiceClient(cc grpc.ClientConnInterface) CoffeeServiceClient {
	return &coffeeServiceClient{cc}
}

func (c *coffeeServiceClient) Add(ctx context.Context, in *CoffeeAddRequest, opts ...grpc.CallOption) (*Coffee, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Coffee)
	err := c.cc.Invoke(ctx, CoffeeService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) Get(ctx context.Context, in *CoffeeGetRequest, opts ...grpc.CallOption) (*Coffee, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Coffee)
	err := c.cc.Invoke(ctx, CoffeeService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) Patch(ctx context.Context, in *CoffeePatchRequest, opts ...grpc.CallOption) (*Coffee, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Coffee)
	err := c.cc.Invoke(ctx, CoffeeService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) Apply(ctx context.Context, in *CoffeeApplyRequest, opts ...grpc.CallOption) (*Coffee, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Coffee)
	err := c.cc.Invoke(ctx, CoffeeService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) Erase(ctx context.Context, in *CoffeeRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CoffeeService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) List(ctx context.Context, in *CoffeeListRequest, opts ...grpc.CallOption) (*CoffeeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoffeeListResponse)
	err := c.cc.Invoke(ctx, CoffeeService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) Watch(ctx context.Context, in *CoffeeWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CoffeeWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoffeeService_ServiceDesc.Streams[0], CoffeeService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CoffeeWatchRequest, CoffeeWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeService_WatchClient = grpc.ServerStreamingClient[CoffeeWatchResponse]

// CoffeeServiceServer is the server API for CoffeeService service.
// All implementations must embed UnimplementedCoffeeServiceServer
// for forward compatibility.
type CoffeeServiceServer interface {
	// Add creates a new Coffee
	Add(context.Context, *CoffeeAddRequest) (*Coffee, error)
	// Get retrieves a Coffee
	Get(context.Context, *CoffeeGetRequest) (*Coffee, error)
	// Patch updates an existing Coffee
	Patch(context.Context, *CoffeePatchRequest) (*Coffee, error)
	// Apply applies a patch document to an existing Coffee
	Apply(context.Context, *CoffeeApplyRequest) (*Coffee, error)
	// Erase deletes a Coffee
	Erase(context.Context, *CoffeeRef) (*emptypb.Empty, error)
	// List the Coffees that match any of the given filters, a page at a time.
	List(context.Context, *CoffeeListRequest) (*CoffeeListResponse, error)
	// Watch the Coffees a caller may see, as they are now and as they change.
	//
	// What arrives is state and never a delta, so a client converges rather than
	// replays: it keeps what it was last told about a Coffee and replaces it. An
	// event it did not receive is one it does not need, since the next one about
	// that Coffee carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A Coffee may arrive twice
	// -- once in that first message and once as a change that happened while it
	// was being read -- and that is harmless for the same reason.
	Watch(*CoffeeWatchRequest, grpc.ServerStreamingServer[CoffeeWatchResponse]) error
	mustEmbedUnimplementedCoffeeServiceServer()
}

// UnimplementedCoffeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeServiceServer struct{}

func (UnimplementedCoffeeServiceServer) Add(context.Context, *CoffeeAddRequest) (*Coffee, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCoffeeServiceServer) Get(context.Context, *CoffeeGetRequest) (*Coffee, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCoffeeServiceServer) Patch(context.Context, *CoffeePatchRequest) (*Coffee, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedCoffeeServiceServer) Apply(context.Context, *CoffeeApplyRequest) (*Coffee, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedCoffeeServiceServer) Erase(context.Context, *CoffeeRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedCoffeeServiceServer) List(context.Context, *CoffeeListRequest) (*CoffeeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCoffeeServiceServer) Watch(*CoffeeWatchRequest, grpc.ServerStreamingServer[CoffeeWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedCoffeeServiceServer) mustEmbedUnimplementedCoffeeServiceServer() {}
func (UnimplementedCoffeeServiceServer) testEmbeddedByValue()                       {}

// UnsafeCoffeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeServiceServer will
// result in compilation errors.
type UnsafeCoffeeServiceServer interface {
	mustEmbedUnimplementedCoffeeServiceServer()
}

func RegisterCoffeeServiceServer(s grpc.ServiceRegistrar, srv CoffeeServiceServer) {
	// If the following call panics, it indicates UnimplementedCoffeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeeService_ServiceDesc, srv)
}

func _CoffeeService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).Add(ctx, req.(*CoffeeAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).Get(ctx, req.(*CoffeeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeePatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).Patch(ctx, req.(*CoffeePatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).Apply(ctx, req.(*CoffeeApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).Erase(ctx, req.(*CoffeeRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).List(ctx, req.(*CoffeeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CoffeeWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoffeeServiceServer).Watch(m, &grpc.GenericServerStream[CoffeeWatchRequest, CoffeeWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoffeeService_WatchServer = grpc.ServerStreamingServer[CoffeeWatchResponse]

// CoffeeService_ServiceDesc is the grpc.ServiceDesc for CoffeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_app.CoffeeService",
	HandlerType: (*CoffeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _CoffeeService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CoffeeService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _CoffeeService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _CoffeeService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _CoffeeService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CoffeeService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _CoffeeService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "go_app/coffee_svc.proto",
}
