// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/holder_svc.proto

package go_app

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HolderAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderAddRequest) Reset() {
	*x = HolderAddRequest{}
	mi := &file_go_app_holder_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderAddRequest) ProtoMessage() {}

func (x *HolderAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *HolderAddRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *HolderAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *HolderAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *HolderAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *HolderAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *HolderAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *HolderAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *HolderAddRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *HolderAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *HolderAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *HolderAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *HolderAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *HolderAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *HolderAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderAddRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *HolderAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *HolderAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *HolderAddRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *HolderAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type HolderAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Tenant      *TenantRef
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	DateCreated *timestamppb.Timestamp
}

func (b0 HolderAddRequest_builder) Build() *HolderAddRequest {
	m0 := &HolderAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type HolderGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *HolderSelect          `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HolderGetRequest) Reset() {
	*x = HolderGetRequest{}
	mi := &file_go_app_holder_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderGetRequest) ProtoMessage() {}

func (x *HolderGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderGetRequest) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderGetRequest) GetSelect() *HolderSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *HolderGetRequest) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderGetRequest) SetSelect(v *HolderSelect) {
	x.xxx_hidden_Select = v
}

func (x *HolderGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *HolderGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *HolderGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type HolderGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *HolderRef
	Select *HolderSelect
}

func (b0 HolderGetRequest_builder) Build() *HolderGetRequest {
	m0 := &HolderGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type HolderRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isHolderRef_Key        `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HolderRef) Reset() {
	*x = HolderRef{}
	mi := &file_go_app_holder_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderRef) ProtoMessage() {}

func (x *HolderRef) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*holderRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *HolderRef) GetSlug() *HolderRefBySlug {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*holderRef_Slug); ok {
			return x.Slug
		}
	}
	return nil
}

func (x *HolderRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &holderRef_Id{v}
}

func (x *HolderRef) SetSlug(v *HolderRefBySlug) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &holderRef_Slug{v}
}

func (x *HolderRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *HolderRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*holderRef_Id)
	return ok
}

func (x *HolderRef) HasSlug() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*holderRef_Slug)
	return ok
}

func (x *HolderRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *HolderRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*holderRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *HolderRef) ClearSlug() {
	if _, ok := x.xxx_hidden_Key.(*holderRef_Slug); ok {
		x.xxx_hidden_Key = nil
	}
}

const HolderRef_Key_not_set_case case_HolderRef_Key = 0
const HolderRef_Id_case case_HolderRef_Key = 1
const HolderRef_Slug_case case_HolderRef_Key = 4

func (x *HolderRef) WhichKey() case_HolderRef_Key {
	if x == nil {
		return HolderRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *holderRef_Id:
		return HolderRef_Id_case
	case *holderRef_Slug:
		return HolderRef_Slug_case
	default:
		return HolderRef_Key_not_set_case
	}
}

type HolderRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id   []byte
	Slug *HolderRefBySlug
	// -- end of xxx_hidden_Key
}

func (b0 HolderRef_builder) Build() *HolderRef {
	m0 := &HolderRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &holderRef_Id{b.Id}
	}
	if b.Slug != nil {
		x.xxx_hidden_Key = &holderRef_Slug{b.Slug}
	}
	return m0
}

type case_HolderRef_Key protoreflect.FieldNumber

func (x case_HolderRef_Key) String() string {
	md := file_go_app_holder_svc_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isHolderRef_Key interface {
	isHolderRef_Key()
}

type holderRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type holderRef_Slug struct {
	Slug *HolderRefBySlug `protobuf:"bytes,4,opt,name=slug,oneof"`
}

func (*holderRef_Id) isHolderRef_Key() {}

func (*holderRef_Slug) isHolderRef_Key() {}

type HolderRefBySlug struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderRefBySlug) Reset() {
	*x = HolderRefBySlug{}
	mi := &file_go_app_holder_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderRefBySlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderRefBySlug) ProtoMessage() {}

func (x *HolderRefBySlug) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderRefBySlug) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *HolderRefBySlug) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *HolderRefBySlug) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *HolderRefBySlug) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *HolderRefBySlug) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderRefBySlug) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *HolderRefBySlug) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *HolderRefBySlug) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type HolderRefBySlug_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias  *string
	Tenant *TenantRef
}

func (b0 HolderRefBySlug_builder) Build() *HolderRefBySlug {
	m0 := &HolderRefBySlug{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_Tenant = b.Tenant
	return m0
}

type HolderSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Tenant      *TenantSelect          `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_DateErased  bool                   `protobuf:"varint,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderSelect) Reset() {
	*x = HolderSelect{}
	mi := &file_go_app_holder_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderSelect) ProtoMessage() {}

func (x *HolderSelect) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *HolderSelect) GetTenant() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *HolderSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *HolderSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *HolderSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *HolderSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *HolderSelect) GetDateErased() bool {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return false
}

func (x *HolderSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *HolderSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *HolderSelect) SetTenant(v *TenantSelect) {
	x.xxx_hidden_Tenant = v
}

func (x *HolderSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *HolderSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *HolderSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *HolderSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *HolderSelect) SetDateErased(v bool) {
	x.xxx_hidden_DateErased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *HolderSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *HolderSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderSelect) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *HolderSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HolderSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HolderSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *HolderSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *HolderSelect) HasDateErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *HolderSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *HolderSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *HolderSelect) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *HolderSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = false
}

func (x *HolderSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = false
}

func (x *HolderSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Desc = false
}

func (x *HolderSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Labels = false
}

func (x *HolderSelect) ClearDateErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateErased = false
}

func (x *HolderSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateCreated = false
}

type HolderSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Tenant      *TenantSelect
	Alias       *bool
	Name        *bool
	Desc        *bool
	Labels      *bool
	DateErased  *bool
	DateCreated *bool
}

func (b0 HolderSelect_builder) Build() *HolderSelect {
	m0 := &HolderSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.DateErased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_DateErased = *b.DateErased
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type HolderPatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,8,opt,name=alias"`
	xxx_hidden_Name        *string                `protobuf:"bytes,10,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,12,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,14,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderPatchRequest) Reset() {
	*x = HolderPatchRequest{}
	mi := &file_go_app_holder_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderPatchRequest) ProtoMessage() {}

func (x *HolderPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderPatchRequest) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *HolderPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *HolderPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *HolderPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *HolderPatchRequest) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *HolderPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *HolderPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *HolderPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *HolderPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HolderPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HolderPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HolderPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *HolderPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *HolderPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *HolderPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

type HolderPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *HolderRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
}

func (b0 HolderPatchRequest_builder) Build() *HolderPatchRequest {
	m0 := &HolderPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type HolderApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HolderApplyRequest) Reset() {
	*x = HolderApplyRequest{}
	mi := &file_go_app_holder_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderApplyRequest) ProtoMessage() {}

func (x *HolderApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderApplyRequest) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *HolderApplyRequest) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *HolderApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *HolderApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *HolderApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type HolderApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *HolderRef
	Patch *patchpb.Patch
}

func (b0 HolderApplyRequest_builder) Build() *HolderApplyRequest {
	m0 := &HolderApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type HolderListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters     *[]*HolderFilter       `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size        int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After       *string                `protobuf:"bytes,3,opt,name=after"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderListRequest) Reset() {
	*x = HolderListRequest{}
	mi := &file_go_app_holder_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderListRequest) ProtoMessage() {}

func (x *HolderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderListRequest) GetFilters() []*HolderFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *HolderListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *HolderListRequest) GetAfter() string {
	if x != nil {
		if x.xxx_hidden_After != nil {
			return *x.xxx_hidden_After
		}
		return ""
	}
	return ""
}

func (x *HolderListRequest) SetFilters(v []*HolderFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *HolderListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *HolderListRequest) SetAfter(v string) {
	x.xxx_hidden_After = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *HolderListRequest) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HolderListRequest) HasAfter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HolderListRequest) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *HolderListRequest) ClearAfter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_After = nil
}

type HolderListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is; see `AuditListRequest.filters`.
	Filters []*HolderFilter
	// How many to answer with. Nothing said is `core.PageSize`, and more than
	// `core.PageLimit` is `core.PageLimit` -- a caller asking for more than there
	// is meant no harm, so it is not an error, and it is not the whole table
	// either.
	Size *int32
	// Where to carry on from: the `next` of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a Holder
	// added while a caller is reading does not shift the page under them.
	After *string
}

func (b0 HolderListRequest_builder) Build() *HolderListRequest {
	m0 := &HolderListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Size = *b.Size
	}
	if b.After != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_After = b.After
	}
	return m0
}

type HolderListResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items       *[]*Holder             `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next        *string                `protobuf:"bytes,2,opt,name=next"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderListResponse) Reset() {
	*x = HolderListResponse{}
	mi := &file_go_app_holder_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderListResponse) ProtoMessage() {}

func (x *HolderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderListResponse) GetItems() []*Holder {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *HolderListResponse) GetNext() string {
	if x != nil {
		if x.xxx_hidden_Next != nil {
			return *x.xxx_hidden_Next
		}
		return ""
	}
	return ""
}

func (x *HolderListResponse) SetItems(v []*Holder) {
	x.xxx_hidden_Items = &v
}

func (x *HolderListResponse) SetNext(v string) {
	x.xxx_hidden_Next = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *HolderListResponse) HasNext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HolderListResponse) ClearNext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Next = nil
}

type HolderListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Holder
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing this server can only know by having
	// looked.
	Next *string
}

func (b0 HolderListResponse_builder) Build() *HolderListResponse {
	m0 := &HolderListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.Next != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Next = b.Next
	}
	return m0
}

type HolderFilter struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HolderFilter) Reset() {
	*x = HolderFilter{}
	mi := &file_go_app_holder_svc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderFilter) ProtoMessage() {}

func (x *HolderFilter) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_holder_svc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderFilter) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderFilter) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

type HolderFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *HolderRef
}

func (b0 HolderFilter_builder) Build() *HolderFilter {
	m0 := &HolderFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	return m0
}

var File_go_app_holder_svc_proto protoreflect.FileDescriptor

const file_go_app_holder_svc_proto_rawDesc = "" +
	"\n" +
	"\x17go_app/holder_svc.proto\x12\x06go_app\x1a\x13go_app/holder.proto\x1a\x17go_app/tenant_svc.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\"\xd8\x02\n" +
	"\x10HolderAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.go_app.TenantRefR\x06tenant\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x12<\n" +
	"\x06labels\x18\a \x03(\v2$.go_app.HolderAddRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x10HolderGetRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.HolderRefR\x03ref\x12,\n" +
	"\x06select\x18\x02 \x01(\v2\x14.go_app.HolderSelectR\x06select\"S\n" +
	"\tHolderRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12-\n" +
	"\x04slug\x18\x04 \x01(\v2\x17.go_app.HolderRefBySlugH\x00R\x04slugB\x05\n" +
	"\x03key\"R\n" +
	"\x0fHolderRefBySlug\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.go_app.TenantRefR\x06tenant\"\xe8\x01\n" +
	"\fHolderSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12,\n" +
	"\x06tenant\x18\x02 \x01(\v2\x14.go_app.TenantSelectR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12\x1f\n" +
	"\vdate_erased\x18\x0e \x01(\bR\n" +
	"dateErased\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\xf2\x01\n" +
	"\x12HolderPatchRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.HolderRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\f \x01(\tR\x04desc\x12>\n" +
	"\x06labels\x18\x0e \x03(\v2&.go_app.HolderPatchRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x12HolderApplyRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.HolderRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"m\n" +
	"\x11HolderListRequest\x12.\n" +
	"\afilters\x18\x01 \x03(\v2\x14.go_app.HolderFilterR\afilters\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\"N\n" +
	"\x12HolderListResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.go_app.HolderR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"3\n" +
	"\fHolderFilter\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.go_app.HolderRefR\x03ref2\xce\x02\n" +
	"\rHolderService\x12/\n" +
	"\x03Add\x12\x18.go_app.HolderAddRequest\x1a\x0e.go_app.Holder\x12/\n" +
	"\x03Get\x12\x18.go_app.HolderGetRequest\x1a\x0e.go_app.Holder\x123\n" +
	"\x05Patch\x12\x1a.go_app.HolderPatchRequest\x1a\x0e.go_app.Holder\x123\n" +
	"\x05Apply\x12\x1a.go_app.HolderApplyRequest\x1a\x0e.go_app.Holder\x122\n" +
	"\x05Erase\x12\x11.go_app.HolderRef\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x04List\x12\x19.go_app.HolderListRequest\x1a\x1a.go_app.HolderListResponseB\x1cZ\x1agithub.com/lesomnus/go-appb\beditionsp\xe8\a"

var file_go_app_holder_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_go_app_holder_svc_proto_goTypes = []any{
	(*HolderAddRequest)(nil),      // 0: go_app.HolderAddRequest
	(*HolderGetRequest)(nil),      // 1: go_app.HolderGetRequest
	(*HolderRef)(nil),             // 2: go_app.HolderRef
	(*HolderRefBySlug)(nil),       // 3: go_app.HolderRefBySlug
	(*HolderSelect)(nil),          // 4: go_app.HolderSelect
	(*HolderPatchRequest)(nil),    // 5: go_app.HolderPatchRequest
	(*HolderApplyRequest)(nil),    // 6: go_app.HolderApplyRequest
	(*HolderListRequest)(nil),     // 7: go_app.HolderListRequest
	(*HolderListResponse)(nil),    // 8: go_app.HolderListResponse
	(*HolderFilter)(nil),          // 9: go_app.HolderFilter
	nil,                           // 10: go_app.HolderAddRequest.LabelsEntry
	nil,                           // 11: go_app.HolderPatchRequest.LabelsEntry
	(*TenantRef)(nil),             // 12: go_app.TenantRef
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*TenantSelect)(nil),          // 14: go_app.TenantSelect
	(*patchpb.Patch)(nil),         // 15: patch.Patch
	(*Holder)(nil),                // 16: go_app.Holder
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_go_app_holder_svc_proto_depIdxs = []int32{
	12, // 0: go_app.HolderAddRequest.tenant:type_name -> go_app.TenantRef
	10, // 1: go_app.HolderAddRequest.labels:type_name -> go_app.HolderAddRequest.LabelsEntry
	13, // 2: go_app.HolderAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 3: go_app.HolderGetRequest.ref:type_name -> go_app.HolderRef
	4,  // 4: go_app.HolderGetRequest.select:type_name -> go_app.HolderSelect
	3,  // 5: go_app.HolderRef.slug:type_name -> go_app.HolderRefBySlug
	12, // 6: go_app.HolderRefBySlug.tenant:type_name -> go_app.TenantRef
	14, // 7: go_app.HolderSelect.tenant:type_name -> go_app.TenantSelect
	2,  // 8: go_app.HolderPatchRequest.ref:type_name -> go_app.HolderRef
	11, // 9: go_app.HolderPatchRequest.labels:type_name -> go_app.HolderPatchRequest.LabelsEntry
	2,  // 10: go_app.HolderApplyRequest.ref:type_name -> go_app.HolderRef
	15, // 11: go_app.HolderApplyRequest.patch:type_name -> patch.Patch
	9,  // 12: go_app.HolderListRequest.filters:type_name -> go_app.HolderFilter
	16, // 13: go_app.HolderListResponse.items:type_name -> go_app.Holder
	2,  // 14: go_app.HolderFilter.ref:type_name -> go_app.HolderRef
	0,  // 15: go_app.HolderService.Add:input_type -> go_app.HolderAddRequest
	1,  // 16: go_app.HolderService.Get:input_type -> go_app.HolderGetRequest
	5,  // 17: go_app.HolderService.Patch:input_type -> go_app.HolderPatchRequest
	6,  // 18: go_app.HolderService.Apply:input_type -> go_app.HolderApplyRequest
	2,  // 19: go_app.HolderService.Erase:input_type -> go_app.HolderRef
	7,  // 20: go_app.HolderService.List:input_type -> go_app.HolderListRequest
	16, // 21: go_app.HolderService.Add:output_type -> go_app.Holder
	16, // 22: go_app.HolderService.Get:output_type -> go_app.Holder
	16, // 23: go_app.HolderService.Patch:output_type -> go_app.Holder
	16, // 24: go_app.HolderService.Apply:output_type -> go_app.Holder
	17, // 25: go_app.HolderService.Erase:output_type -> google.protobuf.Empty
	8,  // 26: go_app.HolderService.List:output_type -> go_app.HolderListResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_go_app_holder_svc_proto_init() }
func file_go_app_holder_svc_proto_init() {
	if File_go_app_holder_svc_proto != nil {
		return
	}
	file_go_app_holder_proto_init()
	file_go_app_tenant_svc_proto_init()
	file_go_app_holder_svc_proto_msgTypes[2].OneofWrappers = []any{
		(*holderRef_Id)(nil),
		(*holderRef_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_holder_svc_proto_rawDesc), len(file_go_app_holder_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_app_holder_svc_proto_goTypes,
		DependencyIndexes: file_go_app_holder_svc_proto_depIdxs,
		MessageInfos:      file_go_app_holder_svc_proto_msgTypes,
	}.Build()
	File_go_app_holder_svc_proto = out.File
	file_go_app_holder_svc_proto_goTypes = nil
	file_go_app_holder_svc_proto_depIdxs = nil
}
