// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: go_app/roaster_svc.proto

package go_app

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoasterService_Add_FullMethodName   = "/go_app.RoasterService/Add"
	RoasterService_Get_FullMethodName   = "/go_app.RoasterService/Get"
	RoasterService_Patch_FullMethodName = "/go_app.RoasterService/Patch"
	RoasterService_Apply_FullMethodName = "/go_app.RoasterService/Apply"
	RoasterService_Erase_FullMethodName = "/go_app.RoasterService/Erase"
	RoasterService_List_FullMethodName  = "/go_app.RoasterService/List"
	RoasterService_Watch_FullMethodName = "/go_app.RoasterService/Watch"
)

// RoasterServiceClient is the client API for RoasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoasterServiceClient interface {
	// Add creates a new Roaster
	Add(ctx context.Context, in *RoasterAddRequest, opts ...grpc.CallOption) (*Roaster, error)
	// Get retrieves a Roaster
	Get(ctx context.Context, in *RoasterGetRequest, opts ...grpc.CallOption) (*Roaster, error)
	// Patch updates an existing Roaster
	Patch(ctx context.Context, in *RoasterPatchRequest, opts ...grpc.CallOption) (*Roaster, error)
	// Apply applies a patch document to an existing Roaster
	Apply(ctx context.Context, in *RoasterApplyRequest, opts ...grpc.CallOption) (*Roaster, error)
	// Erase deletes a Roaster
	Erase(ctx context.Context, in *RoasterRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List the Roasters that match any of the given filters, a page at a time.
	List(ctx context.Context, in *RoasterListRequest, opts ...grpc.CallOption) (*RoasterListResponse, error)
	// Watch the Roasters, as they are now and as they change. See
	// `CoffeeService.Watch`, which this is in every way.
	Watch(ctx context.Context, in *RoasterWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoasterWatchResponse], error)
}

type roasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoasterServiceClient(cc grpc.ClientConnInterface) RoasterServiceClient {
	return &roasterServiceClient{cc}
}

func (c *roasterServiceClient) Add(ctx context.Context, in *RoasterAddRequest, opts ...grpc.CallOption) (*Roaster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Roaster)
	err := c.cc.Invoke(ctx, RoasterService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roasterServiceClient) Get(ctx context.Context, in *RoasterGetRequest, opts ...grpc.CallOption) (*Roaster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Roaster)
	err := c.cc.Invoke(ctx, RoasterService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roasterServiceClient) Patch(ctx context.Context, in *RoasterPatchRequest, opts ...grpc.CallOption) (*Roaster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Roaster)
	err := c.cc.Invoke(ctx, RoasterService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roasterServiceClient) Apply(ctx context.Context, in *RoasterApplyRequest, opts ...grpc.CallOption) (*Roaster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Roaster)
	err := c.cc.Invoke(ctx, RoasterService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roasterServiceClient) Erase(ctx context.Context, in *RoasterRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoasterService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roasterServiceClient) List(ctx context.Context, in *RoasterListRequest, opts ...grpc.CallOption) (*RoasterListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoasterListResponse)
	err := c.cc.Invoke(ctx, RoasterService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roasterServiceClient) Watch(ctx context.Context, in *RoasterWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoasterWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RoasterService_ServiceDesc.Streams[0], RoasterService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RoasterWatchRequest, RoasterWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoasterService_WatchClient = grpc.ServerStreamingClient[RoasterWatchResponse]

// RoasterServiceServer is the server API for RoasterService service.
// All implementations must embed UnimplementedRoasterServiceServer
// for forward compatibility.
type RoasterServiceServer interface {
	// Add creates a new Roaster
	Add(context.Context, *RoasterAddRequest) (*Roaster, error)
	// Get retrieves a Roaster
	Get(context.Context, *RoasterGetRequest) (*Roaster, error)
	// Patch updates an existing Roaster
	Patch(context.Context, *RoasterPatchRequest) (*Roaster, error)
	// Apply applies a patch document to an existing Roaster
	Apply(context.Context, *RoasterApplyRequest) (*Roaster, error)
	// Erase deletes a Roaster
	Erase(context.Context, *RoasterRef) (*emptypb.Empty, error)
	// List the Roasters that match any of the given filters, a page at a time.
	List(context.Context, *RoasterListRequest) (*RoasterListResponse, error)
	// Watch the Roasters, as they are now and as they change. See
	// `CoffeeService.Watch`, which this is in every way.
	Watch(*RoasterWatchRequest, grpc.ServerStreamingServer[RoasterWatchResponse]) error
	mustEmbedUnimplementedRoasterServiceServer()
}

// UnimplementedRoasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoasterServiceServer struct{}

func (UnimplementedRoasterServiceServer) Add(context.Context, *RoasterAddRequest) (*Roaster, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedRoasterServiceServer) Get(context.Context, *RoasterGetRequest) (*Roaster, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRoasterServiceServer) Patch(context.Context, *RoasterPatchRequest) (*Roaster, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedRoasterServiceServer) Apply(context.Context, *RoasterApplyRequest) (*Roaster, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedRoasterServiceServer) Erase(context.Context, *RoasterRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedRoasterServiceServer) List(context.Context, *RoasterListRequest) (*RoasterListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRoasterServiceServer) Watch(*RoasterWatchRequest, grpc.ServerStreamingServer[RoasterWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedRoasterServiceServer) mustEmbedUnimplementedRoasterServiceServer() {}
func (UnimplementedRoasterServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoasterServiceServer will
// result in compilation errors.
type UnsafeRoasterServiceServer interface {
	mustEmbedUnimplementedRoasterServiceServer()
}

func RegisterRoasterServiceServer(s grpc.ServiceRegistrar, srv RoasterServiceServer) {
	// If the following call panics, it indicates UnimplementedRoasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoasterService_ServiceDesc, srv)
}

func _RoasterService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoasterAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoasterServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoasterService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoasterServiceServer).Add(ctx, req.(*RoasterAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoasterService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoasterGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoasterServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoasterService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoasterServiceServer).Get(ctx, req.(*RoasterGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoasterService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoasterPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoasterServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoasterService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoasterServiceServer).Patch(ctx, req.(*RoasterPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoasterService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoasterApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoasterServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoasterService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoasterServiceServer).Apply(ctx, req.(*RoasterApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoasterService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoasterRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoasterServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoasterService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoasterServiceServer).Erase(ctx, req.(*RoasterRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoasterService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoasterListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoasterServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoasterService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoasterServiceServer).List(ctx, req.(*RoasterListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoasterService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RoasterWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoasterServiceServer).Watch(m, &grpc.GenericServerStream[RoasterWatchRequest, RoasterWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoasterService_WatchServer = grpc.ServerStreamingServer[RoasterWatchResponse]

// RoasterService_ServiceDesc is the grpc.ServiceDesc for RoasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_app.RoasterService",
	HandlerType: (*RoasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _RoasterService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RoasterService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _RoasterService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _RoasterService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _RoasterService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RoasterService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _RoasterService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "go_app/roaster_svc.proto",
}
