// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/roaster.proto

package go_app

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Roaster is somebody who roasts coffee, and is here to be the thing a Coffee
// belongs to.
//
// The pair exists because one entity on its own demonstrates nothing about
// references. An edge, a name that is unique *within* something else, the key
// resolution that points an edge at a row, and a unique index over two columns
// are every one of them things that need a second entity to be shown at all.
type Roaster struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,2,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,4,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,5,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Roaster) Reset() {
	*x = Roaster{}
	mi := &file_go_app_roaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Roaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roaster) ProtoMessage() {}

func (x *Roaster) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Roaster) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Roaster) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Roaster) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Roaster) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Roaster) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Roaster) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Roaster) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Roaster) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Roaster) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Roaster) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Roaster) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *Roaster) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Roaster) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Roaster) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Roaster_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// The name it is known by, unique across every Roaster there is.
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	DateCreated *timestamppb.Timestamp
}

func (b0 Roaster_builder) Build() *Roaster {
	m0 := &Roaster{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_go_app_roaster_proto protoreflect.FileDescriptor

const file_go_app_roaster_proto_rawDesc = "" +
	"\n" +
	"\x14go_app/roaster.proto\x12\x06go_app\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\"\xb0\x02\n" +
	"\aRoaster\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12\x1c\n" +
	"\x05alias\x18\x02 \x01(\tB\x06\xea\x82\x16\x020\x01R\x05alias\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x123\n" +
	"\x06labels\x18\x05 \x03(\v2\x1b.go_app.Roaster.LabelsEntryR\x06labels\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\b\xca\xfc\x15\x04\x12\x02\x10\x01B!Z\x1agithub.com/lesomnus/go-app\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_go_app_roaster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_app_roaster_proto_goTypes = []any{
	(*Roaster)(nil),               // 0: go_app.Roaster
	nil,                           // 1: go_app.Roaster.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_go_app_roaster_proto_depIdxs = []int32{
	1, // 0: go_app.Roaster.labels:type_name -> go_app.Roaster.LabelsEntry
	2, // 1: go_app.Roaster.date_created:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_go_app_roaster_proto_init() }
func file_go_app_roaster_proto_init() {
	if File_go_app_roaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_roaster_proto_rawDesc), len(file_go_app_roaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_app_roaster_proto_goTypes,
		DependencyIndexes: file_go_app_roaster_proto_depIdxs,
		MessageInfos:      file_go_app_roaster_proto_msgTypes,
	}.Build()
	File_go_app_roaster_proto = out.File
	file_go_app_roaster_proto_goTypes = nil
	file_go_app_roaster_proto_depIdxs = nil
}
