// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/roaster_svc.proto

package go_app

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoasterAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,2,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,4,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,5,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoasterAddRequest) Reset() {
	*x = RoasterAddRequest{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterAddRequest) ProtoMessage() {}

func (x *RoasterAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *RoasterAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *RoasterAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *RoasterAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *RoasterAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *RoasterAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *RoasterAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *RoasterAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *RoasterAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *RoasterAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *RoasterAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *RoasterAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *RoasterAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RoasterAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *RoasterAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *RoasterAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type RoasterAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	DateCreated *timestamppb.Timestamp
}

func (b0 RoasterAddRequest_builder) Build() *RoasterAddRequest {
	m0 := &RoasterAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type RoasterGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *RoasterRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *RoasterSelect         `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoasterGetRequest) Reset() {
	*x = RoasterGetRequest{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterGetRequest) ProtoMessage() {}

func (x *RoasterGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterGetRequest) GetRef() *RoasterRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *RoasterGetRequest) GetSelect() *RoasterSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *RoasterGetRequest) SetRef(v *RoasterRef) {
	x.xxx_hidden_Ref = v
}

func (x *RoasterGetRequest) SetSelect(v *RoasterSelect) {
	x.xxx_hidden_Select = v
}

func (x *RoasterGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *RoasterGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *RoasterGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *RoasterGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type RoasterGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *RoasterRef
	Select *RoasterSelect
}

func (b0 RoasterGetRequest_builder) Build() *RoasterGetRequest {
	m0 := &RoasterGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type RoasterRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isRoasterRef_Key       `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoasterRef) Reset() {
	*x = RoasterRef{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterRef) ProtoMessage() {}

func (x *RoasterRef) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*roasterRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *RoasterRef) GetAlias() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*roasterRef_Alias); ok {
			return x.Alias
		}
	}
	return ""
}

func (x *RoasterRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &roasterRef_Id{v}
}

func (x *RoasterRef) SetAlias(v string) {
	x.xxx_hidden_Key = &roasterRef_Alias{v}
}

func (x *RoasterRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *RoasterRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*roasterRef_Id)
	return ok
}

func (x *RoasterRef) HasAlias() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*roasterRef_Alias)
	return ok
}

func (x *RoasterRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *RoasterRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*roasterRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *RoasterRef) ClearAlias() {
	if _, ok := x.xxx_hidden_Key.(*roasterRef_Alias); ok {
		x.xxx_hidden_Key = nil
	}
}

const RoasterRef_Key_not_set_case case_RoasterRef_Key = 0
const RoasterRef_Id_case case_RoasterRef_Key = 1
const RoasterRef_Alias_case case_RoasterRef_Key = 2

func (x *RoasterRef) WhichKey() case_RoasterRef_Key {
	if x == nil {
		return RoasterRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *roasterRef_Id:
		return RoasterRef_Id_case
	case *roasterRef_Alias:
		return RoasterRef_Alias_case
	default:
		return RoasterRef_Key_not_set_case
	}
}

type RoasterRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id    []byte
	Alias *string
	// -- end of xxx_hidden_Key
}

func (b0 RoasterRef_builder) Build() *RoasterRef {
	m0 := &RoasterRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &roasterRef_Id{b.Id}
	}
	if b.Alias != nil {
		x.xxx_hidden_Key = &roasterRef_Alias{*b.Alias}
	}
	return m0
}

type case_RoasterRef_Key protoreflect.FieldNumber

func (x case_RoasterRef_Key) String() string {
	md := file_go_app_roaster_svc_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRoasterRef_Key interface {
	isRoasterRef_Key()
}

type roasterRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type roasterRef_Alias struct {
	Alias string `protobuf:"bytes,2,opt,name=alias,oneof"`
}

func (*roasterRef_Id) isRoasterRef_Key() {}

func (*roasterRef_Alias) isRoasterRef_Key() {}

type RoasterSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,2,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,3,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,4,opt,name=desc"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,5,opt,name=labels"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoasterSelect) Reset() {
	*x = RoasterSelect{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterSelect) ProtoMessage() {}

func (x *RoasterSelect) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *RoasterSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *RoasterSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *RoasterSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *RoasterSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *RoasterSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *RoasterSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *RoasterSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *RoasterSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *RoasterSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *RoasterSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *RoasterSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *RoasterSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RoasterSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RoasterSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RoasterSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RoasterSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *RoasterSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *RoasterSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *RoasterSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = false
}

func (x *RoasterSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = false
}

func (x *RoasterSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = false
}

func (x *RoasterSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Labels = false
}

func (x *RoasterSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_DateCreated = false
}

type RoasterSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Alias       *bool
	Name        *bool
	Desc        *bool
	Labels      *bool
	DateCreated *bool
}

func (b0 RoasterSelect_builder) Build() *RoasterSelect {
	m0 := &RoasterSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_All = *b.All
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type RoasterPatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *RoasterRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        *string                `protobuf:"bytes,6,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,8,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,10,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoasterPatchRequest) Reset() {
	*x = RoasterPatchRequest{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterPatchRequest) ProtoMessage() {}

func (x *RoasterPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterPatchRequest) GetRef() *RoasterRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *RoasterPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *RoasterPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RoasterPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *RoasterPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *RoasterPatchRequest) SetRef(v *RoasterRef) {
	x.xxx_hidden_Ref = v
}

func (x *RoasterPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *RoasterPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *RoasterPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *RoasterPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *RoasterPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *RoasterPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RoasterPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RoasterPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RoasterPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *RoasterPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *RoasterPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *RoasterPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

type RoasterPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *RoasterRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
}

func (b0 RoasterPatchRequest_builder) Build() *RoasterPatchRequest {
	m0 := &RoasterPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type RoasterApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *RoasterRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoasterApplyRequest) Reset() {
	*x = RoasterApplyRequest{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterApplyRequest) ProtoMessage() {}

func (x *RoasterApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterApplyRequest) GetRef() *RoasterRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *RoasterApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *RoasterApplyRequest) SetRef(v *RoasterRef) {
	x.xxx_hidden_Ref = v
}

func (x *RoasterApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *RoasterApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *RoasterApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *RoasterApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *RoasterApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type RoasterApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *RoasterRef
	Patch *patchpb.Patch
}

func (b0 RoasterApplyRequest_builder) Build() *RoasterApplyRequest {
	m0 := &RoasterApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type RoasterListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters     *[]*RoasterFilter      `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size        int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After       *string                `protobuf:"bytes,3,opt,name=after"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoasterListRequest) Reset() {
	*x = RoasterListRequest{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterListRequest) ProtoMessage() {}

func (x *RoasterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterListRequest) GetFilters() []*RoasterFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *RoasterListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *RoasterListRequest) GetAfter() string {
	if x != nil {
		if x.xxx_hidden_After != nil {
			return *x.xxx_hidden_After
		}
		return ""
	}
	return ""
}

func (x *RoasterListRequest) SetFilters(v []*RoasterFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *RoasterListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RoasterListRequest) SetAfter(v string) {
	x.xxx_hidden_After = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RoasterListRequest) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RoasterListRequest) HasAfter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RoasterListRequest) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *RoasterListRequest) ClearAfter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_After = nil
}

type RoasterListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is; see `CoffeeListRequest.filters`.
	Filters []*RoasterFilter
	// How many to answer with, and where to carry on from; see
	// `CoffeeListRequest`.
	Size  *int32
	After *string
}

func (b0 RoasterListRequest_builder) Build() *RoasterListRequest {
	m0 := &RoasterListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Size = *b.Size
	}
	if b.After != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_After = b.After
	}
	return m0
}

type RoasterListResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items       *[]*Roaster            `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next        *string                `protobuf:"bytes,2,opt,name=next"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoasterListResponse) Reset() {
	*x = RoasterListResponse{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterListResponse) ProtoMessage() {}

func (x *RoasterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterListResponse) GetItems() []*Roaster {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *RoasterListResponse) GetNext() string {
	if x != nil {
		if x.xxx_hidden_Next != nil {
			return *x.xxx_hidden_Next
		}
		return ""
	}
	return ""
}

func (x *RoasterListResponse) SetItems(v []*Roaster) {
	x.xxx_hidden_Items = &v
}

func (x *RoasterListResponse) SetNext(v string) {
	x.xxx_hidden_Next = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RoasterListResponse) HasNext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RoasterListResponse) ClearNext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Next = nil
}

type RoasterListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Roaster
	// What to ask for next, and empty when this was the last of them.
	Next *string
}

func (b0 RoasterListResponse_builder) Build() *RoasterListResponse {
	m0 := &RoasterListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.Next != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Next = b.Next
	}
	return m0
}

type RoasterFilter struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref *RoasterRef            `protobuf:"bytes,1,opt,name=ref"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoasterFilter) Reset() {
	*x = RoasterFilter{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterFilter) ProtoMessage() {}

func (x *RoasterFilter) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterFilter) GetRef() *RoasterRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *RoasterFilter) SetRef(v *RoasterRef) {
	x.xxx_hidden_Ref = v
}

func (x *RoasterFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *RoasterFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

type RoasterFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *RoasterRef
}

func (b0 RoasterFilter_builder) Build() *RoasterFilter {
	m0 := &RoasterFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	return m0
}

type RoasterWatchRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*RoasterFilter      `protobuf:"bytes,1,rep,name=filters"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoasterWatchRequest) Reset() {
	*x = RoasterWatchRequest{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterWatchRequest) ProtoMessage() {}

func (x *RoasterWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterWatchRequest) GetFilters() []*RoasterFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *RoasterWatchRequest) SetFilters(v []*RoasterFilter) {
	x.xxx_hidden_Filters = &v
}

type RoasterWatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which Roasters to watch, in the same words `List` takes them.
	Filters []*RoasterFilter
}

func (b0 RoasterWatchRequest_builder) Build() *RoasterWatchRequest {
	m0 := &RoasterWatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	return m0
}

type RoasterWatchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*RoasterWatchItem   `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoasterWatchResponse) Reset() {
	*x = RoasterWatchResponse{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterWatchResponse) ProtoMessage() {}

func (x *RoasterWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterWatchResponse) GetItems() []*RoasterWatchItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *RoasterWatchResponse) SetItems(v []*RoasterWatchItem) {
	x.xxx_hidden_Items = &v
}

type RoasterWatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*RoasterWatchItem
}

func (b0 RoasterWatchResponse_builder) Build() *RoasterWatchResponse {
	m0 := &RoasterWatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type RoasterWatchItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       *Roaster               `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Action      *string                `protobuf:"bytes,3,opt,name=action"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoasterWatchItem) Reset() {
	*x = RoasterWatchItem{}
	mi := &file_go_app_roaster_svc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoasterWatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoasterWatchItem) ProtoMessage() {}

func (x *RoasterWatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_roaster_svc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoasterWatchItem) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *RoasterWatchItem) GetValue() *Roaster {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *RoasterWatchItem) GetAction() string {
	if x != nil {
		if x.xxx_hidden_Action != nil {
			return *x.xxx_hidden_Action
		}
		return ""
	}
	return ""
}

func (x *RoasterWatchItem) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RoasterWatchItem) SetValue(v *Roaster) {
	x.xxx_hidden_Value = v
}

func (x *RoasterWatchItem) SetAction(v string) {
	x.xxx_hidden_Action = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RoasterWatchItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RoasterWatchItem) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *RoasterWatchItem) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RoasterWatchItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *RoasterWatchItem) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *RoasterWatchItem) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Action = nil
}

type RoasterWatchItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which Roaster. Always said, since one that is gone still has to be named.
	Id []byte
	// The Roaster as it is now, and absent when there is no longer one to see.
	// See `CoffeeWatchItem.value`.
	//
	// A Roaster is erased for real rather than softly, so absence here is the
	// only thing there could ever have been to say about one that is gone.
	Value *Roaster
	// The RPC that changed it. See `CoffeeWatchItem.action`.
	Action *string
}

func (b0 RoasterWatchItem_builder) Build() *RoasterWatchItem {
	m0 := &RoasterWatchItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Value = b.Value
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Action = b.Action
	}
	return m0
}

var File_go_app_roaster_svc_proto protoreflect.FileDescriptor

const file_go_app_roaster_svc_proto_rawDesc = "" +
	"\n" +
	"\x18go_app/roaster_svc.proto\x12\x06go_app\x1a\x14go_app/roaster.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\"\xaf\x02\n" +
	"\x11RoasterAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1b\n" +
	"\x05alias\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x12=\n" +
	"\x06labels\x18\x05 \x03(\v2%.go_app.RoasterAddRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x11RoasterGetRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.go_app.RoasterRefR\x03ref\x12-\n" +
	"\x06select\x18\x02 \x01(\v2\x15.go_app.RoasterSelectR\x06select\"=\n" +
	"\n" +
	"RoasterRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12\x16\n" +
	"\x05alias\x18\x02 \x01(\tH\x00R\x05aliasB\x05\n" +
	"\x03key\"\x9a\x01\n" +
	"\rRoasterSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x03 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\x05 \x01(\bR\x06labels\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\xf5\x01\n" +
	"\x13RoasterPatchRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.go_app.RoasterRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\b \x01(\tR\x04desc\x12?\n" +
	"\x06labels\x18\n" +
	" \x03(\v2'.go_app.RoasterPatchRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x13RoasterApplyRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.go_app.RoasterRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"o\n" +
	"\x12RoasterListRequest\x12/\n" +
	"\afilters\x18\x01 \x03(\v2\x15.go_app.RoasterFilterR\afilters\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\"P\n" +
	"\x13RoasterListResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.go_app.RoasterR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"5\n" +
	"\rRoasterFilter\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.go_app.RoasterRefR\x03ref\"F\n" +
	"\x13RoasterWatchRequest\x12/\n" +
	"\afilters\x18\x01 \x03(\v2\x15.go_app.RoasterFilterR\afilters\"F\n" +
	"\x14RoasterWatchResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.go_app.RoasterWatchItemR\x05items\"a\n" +
	"\x10RoasterWatchItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.go_app.RoasterR\x05value\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action2\xa0\x03\n" +
	"\x0eRoasterService\x121\n" +
	"\x03Add\x12\x19.go_app.RoasterAddRequest\x1a\x0f.go_app.Roaster\x121\n" +
	"\x03Get\x12\x19.go_app.RoasterGetRequest\x1a\x0f.go_app.Roaster\x125\n" +
	"\x05Patch\x12\x1b.go_app.RoasterPatchRequest\x1a\x0f.go_app.Roaster\x125\n" +
	"\x05Apply\x12\x1b.go_app.RoasterApplyRequest\x1a\x0f.go_app.Roaster\x123\n" +
	"\x05Erase\x12\x12.go_app.RoasterRef\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x04List\x12\x1a.go_app.RoasterListRequest\x1a\x1b.go_app.RoasterListResponse\x12D\n" +
	"\x05Watch\x12\x1b.go_app.RoasterWatchRequest\x1a\x1c.go_app.RoasterWatchResponse0\x01B\x1cZ\x1agithub.com/lesomnus/go-appb\beditionsp\xe8\a"

var file_go_app_roaster_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_go_app_roaster_svc_proto_goTypes = []any{
	(*RoasterAddRequest)(nil),     // 0: go_app.RoasterAddRequest
	(*RoasterGetRequest)(nil),     // 1: go_app.RoasterGetRequest
	(*RoasterRef)(nil),            // 2: go_app.RoasterRef
	(*RoasterSelect)(nil),         // 3: go_app.RoasterSelect
	(*RoasterPatchRequest)(nil),   // 4: go_app.RoasterPatchRequest
	(*RoasterApplyRequest)(nil),   // 5: go_app.RoasterApplyRequest
	(*RoasterListRequest)(nil),    // 6: go_app.RoasterListRequest
	(*RoasterListResponse)(nil),   // 7: go_app.RoasterListResponse
	(*RoasterFilter)(nil),         // 8: go_app.RoasterFilter
	(*RoasterWatchRequest)(nil),   // 9: go_app.RoasterWatchRequest
	(*RoasterWatchResponse)(nil),  // 10: go_app.RoasterWatchResponse
	(*RoasterWatchItem)(nil),      // 11: go_app.RoasterWatchItem
	nil,                           // 12: go_app.RoasterAddRequest.LabelsEntry
	nil,                           // 13: go_app.RoasterPatchRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*patchpb.Patch)(nil),         // 15: patch.Patch
	(*Roaster)(nil),               // 16: go_app.Roaster
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_go_app_roaster_svc_proto_depIdxs = []int32{
	12, // 0: go_app.RoasterAddRequest.labels:type_name -> go_app.RoasterAddRequest.LabelsEntry
	14, // 1: go_app.RoasterAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 2: go_app.RoasterGetRequest.ref:type_name -> go_app.RoasterRef
	3,  // 3: go_app.RoasterGetRequest.select:type_name -> go_app.RoasterSelect
	2,  // 4: go_app.RoasterPatchRequest.ref:type_name -> go_app.RoasterRef
	13, // 5: go_app.RoasterPatchRequest.labels:type_name -> go_app.RoasterPatchRequest.LabelsEntry
	2,  // 6: go_app.RoasterApplyRequest.ref:type_name -> go_app.RoasterRef
	15, // 7: go_app.RoasterApplyRequest.patch:type_name -> patch.Patch
	8,  // 8: go_app.RoasterListRequest.filters:type_name -> go_app.RoasterFilter
	16, // 9: go_app.RoasterListResponse.items:type_name -> go_app.Roaster
	2,  // 10: go_app.RoasterFilter.ref:type_name -> go_app.RoasterRef
	8,  // 11: go_app.RoasterWatchRequest.filters:type_name -> go_app.RoasterFilter
	11, // 12: go_app.RoasterWatchResponse.items:type_name -> go_app.RoasterWatchItem
	16, // 13: go_app.RoasterWatchItem.value:type_name -> go_app.Roaster
	0,  // 14: go_app.RoasterService.Add:input_type -> go_app.RoasterAddRequest
	1,  // 15: go_app.RoasterService.Get:input_type -> go_app.RoasterGetRequest
	4,  // 16: go_app.RoasterService.Patch:input_type -> go_app.RoasterPatchRequest
	5,  // 17: go_app.RoasterService.Apply:input_type -> go_app.RoasterApplyRequest
	2,  // 18: go_app.RoasterService.Erase:input_type -> go_app.RoasterRef
	6,  // 19: go_app.RoasterService.List:input_type -> go_app.RoasterListRequest
	9,  // 20: go_app.RoasterService.Watch:input_type -> go_app.RoasterWatchRequest
	16, // 21: go_app.RoasterService.Add:output_type -> go_app.Roaster
	16, // 22: go_app.RoasterService.Get:output_type -> go_app.Roaster
	16, // 23: go_app.RoasterService.Patch:output_type -> go_app.Roaster
	16, // 24: go_app.RoasterService.Apply:output_type -> go_app.Roaster
	17, // 25: go_app.RoasterService.Erase:output_type -> google.protobuf.Empty
	7,  // 26: go_app.RoasterService.List:output_type -> go_app.RoasterListResponse
	10, // 27: go_app.RoasterService.Watch:output_type -> go_app.RoasterWatchResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_go_app_roaster_svc_proto_init() }
func file_go_app_roaster_svc_proto_init() {
	if File_go_app_roaster_svc_proto != nil {
		return
	}
	file_go_app_roaster_proto_init()
	file_go_app_roaster_svc_proto_msgTypes[2].OneofWrappers = []any{
		(*roasterRef_Id)(nil),
		(*roasterRef_Alias)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_roaster_svc_proto_rawDesc), len(file_go_app_roaster_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_app_roaster_svc_proto_goTypes,
		DependencyIndexes: file_go_app_roaster_svc_proto_depIdxs,
		MessageInfos:      file_go_app_roaster_svc_proto_msgTypes,
	}.Build()
	File_go_app_roaster_svc_proto = out.File
	file_go_app_roaster_svc_proto_goTypes = nil
	file_go_app_roaster_svc_proto_depIdxs = nil
}
