// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package go_app

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *UserRef) Pick() *UserGetRequest {
	return UserGetRequest_builder{Ref: x}.Build()
}

func (x *User) Ref() *UserRef {
	if v := x.GetId(); len(v) > 0 {
		return UserById(v)
	}
	{
		v1 := x.GetAlias()
		v2 := x.GetTenant()
		if len(v1) > 0 && v2 != nil {
			return UserBySlug(v1, v2.Ref())
		}
	}

	return nil
}

func (x *User) Pick() *UserGetRequest {
	return x.Ref().Pick()
}

func (x *UserRef) Picks(v *User) bool {
	switch x.WhichKey() {
	case UserRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case UserRef_Slug_case:
		x := x.GetSlug()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetTenant().Picks(v.GetTenant()))
	default:
		return false
	}
}

func (x *UserGetRequest) WithSelect(f func(s *UserSelect)) *UserGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&UserSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *User) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *User) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func UserById(v []byte) *UserRef {
	x := &UserRef{}
	x.SetId(v)
	return x
}

func UserGetById(v []byte) *UserGetRequest {
	return UserGetRequest_builder{Ref: UserById(v)}.Build()
}

func UserBySlug(alias string, tenant *TenantRef) *UserRef {
	x := &UserRefBySlug{}
	x.SetAlias(alias)
	x.SetTenant(tenant)
	return UserRef_builder{Slug: x}.Build()
}

func UserGetBySlug(alias string, tenant *TenantRef) *UserGetRequest {
	return UserGetRequest_builder{Ref: UserBySlug(alias, tenant)}.Build()
}
