// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_app/user_svc.proto

package go_app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserAddRequest) Reset() {
	*x = UserAddRequest{}
	mi := &file_go_app_user_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddRequest) ProtoMessage() {}

func (x *UserAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *UserAddRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *UserAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *UserAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *UserAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *UserAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *UserAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *UserAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *UserAddRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *UserAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *UserAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *UserAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *UserAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *UserAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *UserAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserAddRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *UserAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *UserAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UserAddRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *UserAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type UserAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Tenant      *TenantRef
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	DateCreated *timestamppb.Timestamp
}

func (b0 UserAddRequest_builder) Build() *UserAddRequest {
	m0 := &UserAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type UserGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *UserRef               `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *UserSelect            `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserGetRequest) Reset() {
	*x = UserGetRequest{}
	mi := &file_go_app_user_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetRequest) ProtoMessage() {}

func (x *UserGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserGetRequest) GetRef() *UserRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *UserGetRequest) GetSelect() *UserSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *UserGetRequest) SetRef(v *UserRef) {
	x.xxx_hidden_Ref = v
}

func (x *UserGetRequest) SetSelect(v *UserSelect) {
	x.xxx_hidden_Select = v
}

func (x *UserGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *UserGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *UserGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *UserGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type UserGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *UserRef
	Select *UserSelect
}

func (b0 UserGetRequest_builder) Build() *UserGetRequest {
	m0 := &UserGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type UserRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isUserRef_Key          `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserRef) Reset() {
	*x = UserRef{}
	mi := &file_go_app_user_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRef) ProtoMessage() {}

func (x *UserRef) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*userRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *UserRef) GetSlug() *UserRefBySlug {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*userRef_Slug); ok {
			return x.Slug
		}
	}
	return nil
}

func (x *UserRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &userRef_Id{v}
}

func (x *UserRef) SetSlug(v *UserRefBySlug) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &userRef_Slug{v}
}

func (x *UserRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *UserRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*userRef_Id)
	return ok
}

func (x *UserRef) HasSlug() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*userRef_Slug)
	return ok
}

func (x *UserRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *UserRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*userRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *UserRef) ClearSlug() {
	if _, ok := x.xxx_hidden_Key.(*userRef_Slug); ok {
		x.xxx_hidden_Key = nil
	}
}

const UserRef_Key_not_set_case case_UserRef_Key = 0
const UserRef_Id_case case_UserRef_Key = 1
const UserRef_Slug_case case_UserRef_Key = 4

func (x *UserRef) WhichKey() case_UserRef_Key {
	if x == nil {
		return UserRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *userRef_Id:
		return UserRef_Id_case
	case *userRef_Slug:
		return UserRef_Slug_case
	default:
		return UserRef_Key_not_set_case
	}
}

type UserRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id   []byte
	Slug *UserRefBySlug
	// -- end of xxx_hidden_Key
}

func (b0 UserRef_builder) Build() *UserRef {
	m0 := &UserRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &userRef_Id{b.Id}
	}
	if b.Slug != nil {
		x.xxx_hidden_Key = &userRef_Slug{b.Slug}
	}
	return m0
}

type case_UserRef_Key protoreflect.FieldNumber

func (x case_UserRef_Key) String() string {
	md := file_go_app_user_svc_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUserRef_Key interface {
	isUserRef_Key()
}

type userRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type userRef_Slug struct {
	Slug *UserRefBySlug `protobuf:"bytes,4,opt,name=slug,oneof"`
}

func (*userRef_Id) isUserRef_Key() {}

func (*userRef_Slug) isUserRef_Key() {}

type UserRefBySlug struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserRefBySlug) Reset() {
	*x = UserRefBySlug{}
	mi := &file_go_app_user_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRefBySlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefBySlug) ProtoMessage() {}

func (x *UserRefBySlug) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserRefBySlug) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *UserRefBySlug) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *UserRefBySlug) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UserRefBySlug) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *UserRefBySlug) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserRefBySlug) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *UserRefBySlug) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *UserRefBySlug) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type UserRefBySlug_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias  *string
	Tenant *TenantRef
}

func (b0 UserRefBySlug_builder) Build() *UserRefBySlug {
	m0 := &UserRefBySlug{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_Tenant = b.Tenant
	return m0
}

type UserSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Tenant      *TenantSelect          `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserSelect) Reset() {
	*x = UserSelect{}
	mi := &file_go_app_user_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSelect) ProtoMessage() {}

func (x *UserSelect) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *UserSelect) GetTenant() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *UserSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *UserSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *UserSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *UserSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *UserSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *UserSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *UserSelect) SetTenant(v *TenantSelect) {
	x.xxx_hidden_Tenant = v
}

func (x *UserSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *UserSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *UserSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *UserSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *UserSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *UserSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserSelect) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *UserSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UserSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UserSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *UserSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *UserSelect) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *UserSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = false
}

func (x *UserSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = false
}

func (x *UserSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Desc = false
}

func (x *UserSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Labels = false
}

func (x *UserSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateCreated = false
}

type UserSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Tenant      *TenantSelect
	Alias       *bool
	Name        *bool
	Desc        *bool
	Labels      *bool
	DateCreated *bool
}

func (b0 UserSelect_builder) Build() *UserSelect {
	m0 := &UserSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type UserPatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *UserRef               `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,7,opt,name=alias"`
	xxx_hidden_Name        *string                `protobuf:"bytes,9,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,11,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,13,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserPatchRequest) Reset() {
	*x = UserPatchRequest{}
	mi := &file_go_app_user_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPatchRequest) ProtoMessage() {}

func (x *UserPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserPatchRequest) GetRef() *UserRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *UserPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *UserPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UserPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *UserPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *UserPatchRequest) SetRef(v *UserRef) {
	x.xxx_hidden_Ref = v
}

func (x *UserPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *UserPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *UserPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *UserPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *UserPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *UserPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *UserPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *UserPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *UserPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

type UserPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *UserRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
}

func (b0 UserPatchRequest_builder) Build() *UserPatchRequest {
	m0 := &UserPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type UserListRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*UserFilter         `protobuf:"bytes,1,rep,name=filters"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_go_app_user_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserListRequest) GetFilters() []*UserFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *UserListRequest) SetFilters(v []*UserFilter) {
	x.xxx_hidden_Filters = &v
}

type UserListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filters []*UserFilter
}

func (b0 UserListRequest_builder) Build() *UserListRequest {
	m0 := &UserListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	return m0
}

type UserListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*User               `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_go_app_user_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserListResponse) GetItems() []*User {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *UserListResponse) SetItems(v []*User) {
	x.xxx_hidden_Items = &v
}

type UserListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*User
}

func (b0 UserListResponse_builder) Build() *UserListResponse {
	m0 := &UserListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type UserFilter struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref *UserRef               `protobuf:"bytes,1,opt,name=ref"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserFilter) Reset() {
	*x = UserFilter{}
	mi := &file_go_app_user_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilter) ProtoMessage() {}

func (x *UserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_go_app_user_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserFilter) GetRef() *UserRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *UserFilter) SetRef(v *UserRef) {
	x.xxx_hidden_Ref = v
}

func (x *UserFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *UserFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

type UserFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *UserRef
}

func (b0 UserFilter_builder) Build() *UserFilter {
	m0 := &UserFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	return m0
}

var File_go_app_user_svc_proto protoreflect.FileDescriptor

const file_go_app_user_svc_proto_rawDesc = "" +
	"\n" +
	"\x15go_app/user_svc.proto\x12\x06go_app\x1a\x17go_app/tenant_svc.proto\x1a\x11go_app/user.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\x0eUserAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.go_app.TenantRefR\x06tenant\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x12:\n" +
	"\x06labels\x18\a \x03(\v2\".go_app.UserAddRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x0eUserGetRequest\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.go_app.UserRefR\x03ref\x12*\n" +
	"\x06select\x18\x02 \x01(\v2\x12.go_app.UserSelectR\x06select\"O\n" +
	"\aUserRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12+\n" +
	"\x04slug\x18\x04 \x01(\v2\x15.go_app.UserRefBySlugH\x00R\x04slugB\x05\n" +
	"\x03key\"P\n" +
	"\rUserRefBySlug\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.go_app.TenantRefR\x06tenant\"\xc5\x01\n" +
	"\n" +
	"UserSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12,\n" +
	"\x06tenant\x18\x02 \x01(\v2\x14.go_app.TenantSelectR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\xec\x01\n" +
	"\x10UserPatchRequest\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.go_app.UserRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\a \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\v \x01(\tR\x04desc\x12<\n" +
	"\x06labels\x18\r \x03(\v2$.go_app.UserPatchRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x0fUserListRequest\x12,\n" +
	"\afilters\x18\x01 \x03(\v2\x12.go_app.UserFilterR\afilters\"6\n" +
	"\x10UserListResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.go_app.UserR\x05items\"/\n" +
	"\n" +
	"UserFilter\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.go_app.UserRefR\x03ref2\x85\x02\n" +
	"\vUserService\x12+\n" +
	"\x03Add\x12\x16.go_app.UserAddRequest\x1a\f.go_app.User\x12+\n" +
	"\x03Get\x12\x16.go_app.UserGetRequest\x1a\f.go_app.User\x12/\n" +
	"\x05Patch\x12\x18.go_app.UserPatchRequest\x1a\f.go_app.User\x120\n" +
	"\x05Erase\x12\x0f.go_app.UserRef\x1a\x16.google.protobuf.Empty\x129\n" +
	"\x04List\x12\x17.go_app.UserListRequest\x1a\x18.go_app.UserListResponseB\x1cZ\x1agithub.com/lesomnus/go-appb\beditionsp\xe8\a"

var file_go_app_user_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_go_app_user_svc_proto_goTypes = []any{
	(*UserAddRequest)(nil),        // 0: go_app.UserAddRequest
	(*UserGetRequest)(nil),        // 1: go_app.UserGetRequest
	(*UserRef)(nil),               // 2: go_app.UserRef
	(*UserRefBySlug)(nil),         // 3: go_app.UserRefBySlug
	(*UserSelect)(nil),            // 4: go_app.UserSelect
	(*UserPatchRequest)(nil),      // 5: go_app.UserPatchRequest
	(*UserListRequest)(nil),       // 6: go_app.UserListRequest
	(*UserListResponse)(nil),      // 7: go_app.UserListResponse
	(*UserFilter)(nil),            // 8: go_app.UserFilter
	nil,                           // 9: go_app.UserAddRequest.LabelsEntry
	nil,                           // 10: go_app.UserPatchRequest.LabelsEntry
	(*TenantRef)(nil),             // 11: go_app.TenantRef
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*TenantSelect)(nil),          // 13: go_app.TenantSelect
	(*User)(nil),                  // 14: go_app.User
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_go_app_user_svc_proto_depIdxs = []int32{
	11, // 0: go_app.UserAddRequest.tenant:type_name -> go_app.TenantRef
	9,  // 1: go_app.UserAddRequest.labels:type_name -> go_app.UserAddRequest.LabelsEntry
	12, // 2: go_app.UserAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 3: go_app.UserGetRequest.ref:type_name -> go_app.UserRef
	4,  // 4: go_app.UserGetRequest.select:type_name -> go_app.UserSelect
	3,  // 5: go_app.UserRef.slug:type_name -> go_app.UserRefBySlug
	11, // 6: go_app.UserRefBySlug.tenant:type_name -> go_app.TenantRef
	13, // 7: go_app.UserSelect.tenant:type_name -> go_app.TenantSelect
	2,  // 8: go_app.UserPatchRequest.ref:type_name -> go_app.UserRef
	10, // 9: go_app.UserPatchRequest.labels:type_name -> go_app.UserPatchRequest.LabelsEntry
	8,  // 10: go_app.UserListRequest.filters:type_name -> go_app.UserFilter
	14, // 11: go_app.UserListResponse.items:type_name -> go_app.User
	2,  // 12: go_app.UserFilter.ref:type_name -> go_app.UserRef
	0,  // 13: go_app.UserService.Add:input_type -> go_app.UserAddRequest
	1,  // 14: go_app.UserService.Get:input_type -> go_app.UserGetRequest
	5,  // 15: go_app.UserService.Patch:input_type -> go_app.UserPatchRequest
	2,  // 16: go_app.UserService.Erase:input_type -> go_app.UserRef
	6,  // 17: go_app.UserService.List:input_type -> go_app.UserListRequest
	14, // 18: go_app.UserService.Add:output_type -> go_app.User
	14, // 19: go_app.UserService.Get:output_type -> go_app.User
	14, // 20: go_app.UserService.Patch:output_type -> go_app.User
	15, // 21: go_app.UserService.Erase:output_type -> google.protobuf.Empty
	7,  // 22: go_app.UserService.List:output_type -> go_app.UserListResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_go_app_user_svc_proto_init() }
func file_go_app_user_svc_proto_init() {
	if File_go_app_user_svc_proto != nil {
		return
	}
	file_go_app_tenant_svc_proto_init()
	file_go_app_user_proto_init()
	file_go_app_user_svc_proto_msgTypes[2].OneofWrappers = []any{
		(*userRef_Id)(nil),
		(*userRef_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_app_user_svc_proto_rawDesc), len(file_go_app_user_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_app_user_svc_proto_goTypes,
		DependencyIndexes: file_go_app_user_svc_proto_depIdxs,
		MessageInfos:      file_go_app_user_svc_proto_msgTypes,
	}.Build()
	File_go_app_user_svc_proto = out.File
	file_go_app_user_svc_proto_goTypes = nil
	file_go_app_user_svc_proto_depIdxs = nil
}
