// Code generated by ent, DO NOT EDIT.

package coffee

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the coffee type in the database.
	Label = "coffee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// EdgeRoaster holds the string denoting the roaster edge name in mutations.
	EdgeRoaster = "roaster"
	// Table holds the table name of the coffee in the database.
	Table = "coffee"
	// RoasterTable is the table that holds the roaster relation/edge.
	RoasterTable = "coffee"
	// RoasterInverseTable is the table name for the Roaster entity.
	// It exists in this package in order to avoid circular dependency with the "roaster" package.
	RoasterInverseTable = "roaster"
	// RoasterColumn is the table column denoting the roaster relation/edge.
	RoasterColumn = "coffee_roaster"
)

// Columns holds all SQL columns for coffee fields.
var Columns = []string{
	FieldID,
	FieldAlias,
	FieldName,
	FieldDesc,
	FieldLabels,
	FieldDateErased,
	FieldDateCreated,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "coffee"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"coffee_roaster",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Coffee queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDesc orders the results by the desc field.
func ByDesc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesc, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByRoasterField orders the results by roaster field.
func ByRoasterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoasterStep(), sql.OrderByField(field, opts...))
	}
}
func newRoasterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoasterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RoasterTable, RoasterColumn),
	)
}
