edition = "2023";

package go_app;

import "go_app/tenant.proto";
import "google/protobuf/timestamp.proto";
import "orm.proto";

option features.field_presence = IMPLICIT;
option go_package = "github.com/lesomnus/go-app";

message User {
  reserved 3;

  bytes id = 1 [(orm.field) = {
    type: TYPE_UUID
    key: true
    default: ""
  }];
  Tenant tenant = 2 [(orm.edge) = {immutable: true}];
  string alias = 4;
  string name = 5;
  string desc = 6;
  map<string, string> labels = 7;

  // Start data field from with the number 8.
  // string data = 8;

  google.protobuf.Timestamp date_created = 15 [(orm.field) = {
    immutable: true
    default: ""
  }];

  option (orm.message) = {
    rpc: {crud: true}
    indexes: [
      {
        name: "slug"
        refs: [
          {
            name: "alias"
            number: 4
          },
          {
            name: "tenant"
            number: 2
          }
        ]
        unique: true
      }
    ]
  };
}
