// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: go_app/coffee.proto

package schema

import (
	ent "entgo.io/ent"
	entsql "entgo.io/ent/dialect/entsql"
	schema "entgo.io/ent/schema"
	edge "entgo.io/ent/schema/edge"
	field "entgo.io/ent/schema/field"
	index "entgo.io/ent/schema/index"
	uuid "github.com/google/uuid"
)

type Coffee struct {
	ent.Schema
}

func (Coffee) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Unique().
			Immutable(),
		field.String("alias"),
		field.String("name"),
		field.String("desc"),
		field.JSON("labels", map[string]string{}).
			Optional(),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}

func (Coffee) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("roaster", Roaster.Type).
			Unique().
			Required().
			Immutable(),
	}
}

func (Coffee) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("alias").
			Edges("roaster").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
	}
}

func (Coffee) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "coffee"},
	}
}
