// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TenantColumns holds the columns for the "tenant" table.
	TenantColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// TenantTable holds the schema information for the "tenant" table.
	TenantTable = &schema.Table{
		Name:       "tenant",
		Columns:    TenantColumns,
		PrimaryKey: []*schema.Column{TenantColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
		{Name: "user_tenant", Type: field.TypeUUID},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tenant_tenant",
				Columns:    []*schema.Column{UserColumns[6]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_alias_user_tenant",
				Unique:  true,
				Columns: []*schema.Column{UserColumns[1], UserColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TenantTable,
		UserTable,
	}
)

func init() {
	TenantTable.Annotation = &entsql.Annotation{
		Table: "tenant",
	}
	UserTable.ForeignKeys[0].RefTable = TenantTable
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
