// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CoffeeColumns holds the columns for the "coffee" table.
	CoffeeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_erased", Type: field.TypeTime, Nullable: true},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
		{Name: "coffee_roaster", Type: field.TypeUUID},
	}
	// CoffeeTable holds the schema information for the "coffee" table.
	CoffeeTable = &schema.Table{
		Name:       "coffee",
		Columns:    CoffeeColumns,
		PrimaryKey: []*schema.Column{CoffeeColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "coffee_roaster_roaster",
				Columns:    []*schema.Column{CoffeeColumns[7]},
				RefColumns: []*schema.Column{RoasterColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "coffee_alias_coffee_roaster",
				Unique:  true,
				Columns: []*schema.Column{CoffeeColumns[1], CoffeeColumns[7]},
				Annotation: &entsql.IndexAnnotation{
					Where: "date_erased IS NULL",
				},
			},
		},
	}
	// RoasterColumns holds the columns for the "roaster" table.
	RoasterColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "alias", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "date_created", Type: field.TypeTime, Nullable: true},
	}
	// RoasterTable holds the schema information for the "roaster" table.
	RoasterTable = &schema.Table{
		Name:       "roaster",
		Columns:    RoasterColumns,
		PrimaryKey: []*schema.Column{RoasterColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CoffeeTable,
		RoasterTable,
	}
)

func init() {
	CoffeeTable.ForeignKeys[0].RefTable = RoasterTable
	CoffeeTable.Annotation = &entsql.Annotation{
		Table: "coffee",
	}
	RoasterTable.Annotation = &entsql.Annotation{
		Table: "roaster",
	}
}
