// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/lesomnus/go-app/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lesomnus/go-app/internal/ent/coffee"
	"github.com/lesomnus/go-app/internal/ent/roaster"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Coffee is the client for interacting with the Coffee builders.
	Coffee *CoffeeClient
	// Roaster is the client for interacting with the Roaster builders.
	Roaster *RoasterClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Coffee = NewCoffeeClient(c.config)
	c.Roaster = NewRoasterClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Coffee:  NewCoffeeClient(cfg),
		Roaster: NewRoasterClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Coffee:  NewCoffeeClient(cfg),
		Roaster: NewRoasterClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Coffee.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Coffee.Use(hooks...)
	c.Roaster.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Coffee.Intercept(interceptors...)
	c.Roaster.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CoffeeMutation:
		return c.Coffee.mutate(ctx, m)
	case *RoasterMutation:
		return c.Roaster.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CoffeeClient is a client for the Coffee schema.
type CoffeeClient struct {
	config
}

// NewCoffeeClient returns a client for the Coffee from the given config.
func NewCoffeeClient(c config) *CoffeeClient {
	return &CoffeeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `coffee.Hooks(f(g(h())))`.
func (c *CoffeeClient) Use(hooks ...Hook) {
	c.hooks.Coffee = append(c.hooks.Coffee, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `coffee.Intercept(f(g(h())))`.
func (c *CoffeeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Coffee = append(c.inters.Coffee, interceptors...)
}

// Create returns a builder for creating a Coffee entity.
func (c *CoffeeClient) Create() *CoffeeCreate {
	mutation := newCoffeeMutation(c.config, OpCreate)
	return &CoffeeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Coffee entities.
func (c *CoffeeClient) CreateBulk(builders ...*CoffeeCreate) *CoffeeCreateBulk {
	return &CoffeeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CoffeeClient) MapCreateBulk(slice any, setFunc func(*CoffeeCreate, int)) *CoffeeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CoffeeCreateBulk{err: fmt.Errorf("calling to CoffeeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CoffeeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CoffeeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Coffee.
func (c *CoffeeClient) Update() *CoffeeUpdate {
	mutation := newCoffeeMutation(c.config, OpUpdate)
	return &CoffeeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CoffeeClient) UpdateOne(_m *Coffee) *CoffeeUpdateOne {
	mutation := newCoffeeMutation(c.config, OpUpdateOne, withCoffee(_m))
	return &CoffeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CoffeeClient) UpdateOneID(id uuid.UUID) *CoffeeUpdateOne {
	mutation := newCoffeeMutation(c.config, OpUpdateOne, withCoffeeID(id))
	return &CoffeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Coffee.
func (c *CoffeeClient) Delete() *CoffeeDelete {
	mutation := newCoffeeMutation(c.config, OpDelete)
	return &CoffeeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CoffeeClient) DeleteOne(_m *Coffee) *CoffeeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CoffeeClient) DeleteOneID(id uuid.UUID) *CoffeeDeleteOne {
	builder := c.Delete().Where(coffee.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CoffeeDeleteOne{builder}
}

// Query returns a query builder for Coffee.
func (c *CoffeeClient) Query() *CoffeeQuery {
	return &CoffeeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCoffee},
		inters: c.Interceptors(),
	}
}

// Get returns a Coffee entity by its id.
func (c *CoffeeClient) Get(ctx context.Context, id uuid.UUID) (*Coffee, error) {
	return c.Query().Where(coffee.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CoffeeClient) GetX(ctx context.Context, id uuid.UUID) *Coffee {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRoaster queries the roaster edge of a Coffee.
func (c *CoffeeClient) QueryRoaster(_m *Coffee) *RoasterQuery {
	query := (&RoasterClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(coffee.Table, coffee.FieldID, id),
			sqlgraph.To(roaster.Table, roaster.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, coffee.RoasterTable, coffee.RoasterColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CoffeeClient) Hooks() []Hook {
	return c.hooks.Coffee
}

// Interceptors returns the client interceptors.
func (c *CoffeeClient) Interceptors() []Interceptor {
	return c.inters.Coffee
}

func (c *CoffeeClient) mutate(ctx context.Context, m *CoffeeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CoffeeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CoffeeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CoffeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CoffeeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Coffee mutation op: %q", m.Op())
	}
}

// RoasterClient is a client for the Roaster schema.
type RoasterClient struct {
	config
}

// NewRoasterClient returns a client for the Roaster from the given config.
func NewRoasterClient(c config) *RoasterClient {
	return &RoasterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `roaster.Hooks(f(g(h())))`.
func (c *RoasterClient) Use(hooks ...Hook) {
	c.hooks.Roaster = append(c.hooks.Roaster, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `roaster.Intercept(f(g(h())))`.
func (c *RoasterClient) Intercept(interceptors ...Interceptor) {
	c.inters.Roaster = append(c.inters.Roaster, interceptors...)
}

// Create returns a builder for creating a Roaster entity.
func (c *RoasterClient) Create() *RoasterCreate {
	mutation := newRoasterMutation(c.config, OpCreate)
	return &RoasterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Roaster entities.
func (c *RoasterClient) CreateBulk(builders ...*RoasterCreate) *RoasterCreateBulk {
	return &RoasterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RoasterClient) MapCreateBulk(slice any, setFunc func(*RoasterCreate, int)) *RoasterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RoasterCreateBulk{err: fmt.Errorf("calling to RoasterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RoasterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RoasterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Roaster.
func (c *RoasterClient) Update() *RoasterUpdate {
	mutation := newRoasterMutation(c.config, OpUpdate)
	return &RoasterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoasterClient) UpdateOne(_m *Roaster) *RoasterUpdateOne {
	mutation := newRoasterMutation(c.config, OpUpdateOne, withRoaster(_m))
	return &RoasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoasterClient) UpdateOneID(id uuid.UUID) *RoasterUpdateOne {
	mutation := newRoasterMutation(c.config, OpUpdateOne, withRoasterID(id))
	return &RoasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Roaster.
func (c *RoasterClient) Delete() *RoasterDelete {
	mutation := newRoasterMutation(c.config, OpDelete)
	return &RoasterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RoasterClient) DeleteOne(_m *Roaster) *RoasterDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RoasterClient) DeleteOneID(id uuid.UUID) *RoasterDeleteOne {
	builder := c.Delete().Where(roaster.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoasterDeleteOne{builder}
}

// Query returns a query builder for Roaster.
func (c *RoasterClient) Query() *RoasterQuery {
	return &RoasterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRoaster},
		inters: c.Interceptors(),
	}
}

// Get returns a Roaster entity by its id.
func (c *RoasterClient) Get(ctx context.Context, id uuid.UUID) (*Roaster, error) {
	return c.Query().Where(roaster.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoasterClient) GetX(ctx context.Context, id uuid.UUID) *Roaster {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RoasterClient) Hooks() []Hook {
	return c.hooks.Roaster
}

// Interceptors returns the client interceptors.
func (c *RoasterClient) Interceptors() []Interceptor {
	return c.inters.Roaster
}

func (c *RoasterClient) mutate(ctx context.Context, m *RoasterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RoasterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RoasterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RoasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RoasterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Roaster mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Coffee, Roaster []ent.Hook
	}
	inters struct {
		Coffee, Roaster []ent.Interceptor
	}
)
