// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lesomnus/go-app/internal/ent/coffee"
	"github.com/lesomnus/go-app/internal/ent/predicate"
)

// CoffeeUpdate is the builder for updating Coffee entities.
type CoffeeUpdate struct {
	config
	hooks     []Hook
	mutation  *CoffeeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CoffeeUpdate builder.
func (_u *CoffeeUpdate) Where(ps ...predicate.Coffee) *CoffeeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *CoffeeUpdate) SetAlias(v string) *CoffeeUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *CoffeeUpdate) SetNillableAlias(v *string) *CoffeeUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CoffeeUpdate) SetName(v string) *CoffeeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CoffeeUpdate) SetNillableName(v *string) *CoffeeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *CoffeeUpdate) SetDesc(v string) *CoffeeUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *CoffeeUpdate) SetNillableDesc(v *string) *CoffeeUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *CoffeeUpdate) SetLabels(v map[string]string) *CoffeeUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *CoffeeUpdate) ClearLabels() *CoffeeUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *CoffeeUpdate) SetDateErased(v time.Time) *CoffeeUpdate {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *CoffeeUpdate) SetNillableDateErased(v *time.Time) *CoffeeUpdate {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *CoffeeUpdate) ClearDateErased() *CoffeeUpdate {
	_u.mutation.ClearDateErased()
	return _u
}

// Mutation returns the CoffeeMutation object of the builder.
func (_u *CoffeeUpdate) Mutation() *CoffeeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoffeeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoffeeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoffeeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoffeeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoffeeUpdate) check() error {
	if _u.mutation.RoasterCleared() && len(_u.mutation.RoasterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Coffee.roaster"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoffeeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoffeeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoffeeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coffee.Table, coffee.Columns, sqlgraph.NewFieldSpec(coffee.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(coffee.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(coffee.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(coffee.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(coffee.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(coffee.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(coffee.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(coffee.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(coffee.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coffee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoffeeUpdateOne is the builder for updating a single Coffee entity.
type CoffeeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CoffeeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAlias sets the "alias" field.
func (_u *CoffeeUpdateOne) SetAlias(v string) *CoffeeUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *CoffeeUpdateOne) SetNillableAlias(v *string) *CoffeeUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CoffeeUpdateOne) SetName(v string) *CoffeeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CoffeeUpdateOne) SetNillableName(v *string) *CoffeeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *CoffeeUpdateOne) SetDesc(v string) *CoffeeUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *CoffeeUpdateOne) SetNillableDesc(v *string) *CoffeeUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *CoffeeUpdateOne) SetLabels(v map[string]string) *CoffeeUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *CoffeeUpdateOne) ClearLabels() *CoffeeUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *CoffeeUpdateOne) SetDateErased(v time.Time) *CoffeeUpdateOne {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *CoffeeUpdateOne) SetNillableDateErased(v *time.Time) *CoffeeUpdateOne {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *CoffeeUpdateOne) ClearDateErased() *CoffeeUpdateOne {
	_u.mutation.ClearDateErased()
	return _u
}

// Mutation returns the CoffeeMutation object of the builder.
func (_u *CoffeeUpdateOne) Mutation() *CoffeeMutation {
	return _u.mutation
}

// Where appends a list predicates to the CoffeeUpdate builder.
func (_u *CoffeeUpdateOne) Where(ps ...predicate.Coffee) *CoffeeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoffeeUpdateOne) Select(field string, fields ...string) *CoffeeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Coffee entity.
func (_u *CoffeeUpdateOne) Save(ctx context.Context) (*Coffee, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoffeeUpdateOne) SaveX(ctx context.Context) *Coffee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoffeeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoffeeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoffeeUpdateOne) check() error {
	if _u.mutation.RoasterCleared() && len(_u.mutation.RoasterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Coffee.roaster"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoffeeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoffeeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoffeeUpdateOne) sqlSave(ctx context.Context) (_node *Coffee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coffee.Table, coffee.Columns, sqlgraph.NewFieldSpec(coffee.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Coffee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coffee.FieldID)
		for _, f := range fields {
			if !coffee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coffee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(coffee.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(coffee.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(coffee.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(coffee.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(coffee.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(coffee.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(coffee.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(coffee.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Coffee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coffee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
