// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: go_app/coffee.proto

package ent

import (
	go_app "github.com/lesomnus/go-app/go_app"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Coffee) Proto() *go_app.Coffee {
	x := &go_app.Coffee{}
	x.SetId(e.ID[:])
	if v := e.Edges.Roaster; v != nil {
		x.SetRoaster(v.Proto())
	}
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
