// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lesomnus/go-app/internal/ent/coffee"
	"github.com/lesomnus/go-app/internal/ent/roaster"
)

// CoffeeCreate is the builder for creating a Coffee entity.
type CoffeeCreate struct {
	config
	mutation *CoffeeMutation
	hooks    []Hook
}

// SetAlias sets the "alias" field.
func (_c *CoffeeCreate) SetAlias(v string) *CoffeeCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CoffeeCreate) SetName(v string) *CoffeeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *CoffeeCreate) SetDesc(v string) *CoffeeCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetLabels sets the "labels" field.
func (_c *CoffeeCreate) SetLabels(v map[string]string) *CoffeeCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *CoffeeCreate) SetDateErased(v time.Time) *CoffeeCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *CoffeeCreate) SetNillableDateErased(v *time.Time) *CoffeeCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *CoffeeCreate) SetDateCreated(v time.Time) *CoffeeCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *CoffeeCreate) SetNillableDateCreated(v *time.Time) *CoffeeCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CoffeeCreate) SetID(v uuid.UUID) *CoffeeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRoasterID sets the "roaster" edge to the Roaster entity by ID.
func (_c *CoffeeCreate) SetRoasterID(id uuid.UUID) *CoffeeCreate {
	_c.mutation.SetRoasterID(id)
	return _c
}

// SetRoaster sets the "roaster" edge to the Roaster entity.
func (_c *CoffeeCreate) SetRoaster(v *Roaster) *CoffeeCreate {
	return _c.SetRoasterID(v.ID)
}

// Mutation returns the CoffeeMutation object of the builder.
func (_c *CoffeeCreate) Mutation() *CoffeeMutation {
	return _c.mutation
}

// Save creates the Coffee in the database.
func (_c *CoffeeCreate) Save(ctx context.Context) (*Coffee, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CoffeeCreate) SaveX(ctx context.Context) *Coffee {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoffeeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoffeeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CoffeeCreate) check() error {
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Coffee.alias"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Coffee.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "Coffee.desc"`)}
	}
	if len(_c.mutation.RoasterIDs()) == 0 {
		return &ValidationError{Name: "roaster", err: errors.New(`ent: missing required edge "Coffee.roaster"`)}
	}
	return nil
}

func (_c *CoffeeCreate) sqlSave(ctx context.Context) (*Coffee, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CoffeeCreate) createSpec() (*Coffee, *sqlgraph.CreateSpec) {
	var (
		_node = &Coffee{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coffee.Table, sqlgraph.NewFieldSpec(coffee.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(coffee.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(coffee.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(coffee.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(coffee.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(coffee.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(coffee.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.RoasterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   coffee.RoasterTable,
			Columns: []string{coffee.RoasterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roaster.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.coffee_roaster = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CoffeeCreateBulk is the builder for creating many Coffee entities in bulk.
type CoffeeCreateBulk struct {
	config
	err      error
	builders []*CoffeeCreate
}

// Save creates the Coffee entities in the database.
func (_c *CoffeeCreateBulk) Save(ctx context.Context) ([]*Coffee, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Coffee, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoffeeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CoffeeCreateBulk) SaveX(ctx context.Context) []*Coffee {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoffeeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoffeeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
