// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lesomnus/go-app/internal/ent/predicate"
	"github.com/lesomnus/go-app/internal/ent/roaster"
)

// RoasterUpdate is the builder for updating Roaster entities.
type RoasterUpdate struct {
	config
	hooks     []Hook
	mutation  *RoasterMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RoasterUpdate builder.
func (_u *RoasterUpdate) Where(ps ...predicate.Roaster) *RoasterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *RoasterUpdate) SetAlias(v string) *RoasterUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *RoasterUpdate) SetNillableAlias(v *string) *RoasterUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RoasterUpdate) SetName(v string) *RoasterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoasterUpdate) SetNillableName(v *string) *RoasterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *RoasterUpdate) SetDesc(v string) *RoasterUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *RoasterUpdate) SetNillableDesc(v *string) *RoasterUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *RoasterUpdate) SetLabels(v map[string]string) *RoasterUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *RoasterUpdate) ClearLabels() *RoasterUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// Mutation returns the RoasterMutation object of the builder.
func (_u *RoasterUpdate) Mutation() *RoasterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoasterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoasterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoasterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoasterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RoasterUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RoasterUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RoasterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(roaster.Table, roaster.Columns, sqlgraph.NewFieldSpec(roaster.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(roaster.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(roaster.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(roaster.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(roaster.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(roaster.FieldLabels, field.TypeJSON)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(roaster.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roaster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoasterUpdateOne is the builder for updating a single Roaster entity.
type RoasterUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RoasterMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAlias sets the "alias" field.
func (_u *RoasterUpdateOne) SetAlias(v string) *RoasterUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *RoasterUpdateOne) SetNillableAlias(v *string) *RoasterUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RoasterUpdateOne) SetName(v string) *RoasterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoasterUpdateOne) SetNillableName(v *string) *RoasterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *RoasterUpdateOne) SetDesc(v string) *RoasterUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *RoasterUpdateOne) SetNillableDesc(v *string) *RoasterUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *RoasterUpdateOne) SetLabels(v map[string]string) *RoasterUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *RoasterUpdateOne) ClearLabels() *RoasterUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// Mutation returns the RoasterMutation object of the builder.
func (_u *RoasterUpdateOne) Mutation() *RoasterMutation {
	return _u.mutation
}

// Where appends a list predicates to the RoasterUpdate builder.
func (_u *RoasterUpdateOne) Where(ps ...predicate.Roaster) *RoasterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoasterUpdateOne) Select(field string, fields ...string) *RoasterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Roaster entity.
func (_u *RoasterUpdateOne) Save(ctx context.Context) (*Roaster, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoasterUpdateOne) SaveX(ctx context.Context) *Roaster {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoasterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoasterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RoasterUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RoasterUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RoasterUpdateOne) sqlSave(ctx context.Context) (_node *Roaster, err error) {
	_spec := sqlgraph.NewUpdateSpec(roaster.Table, roaster.Columns, sqlgraph.NewFieldSpec(roaster.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Roaster.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roaster.FieldID)
		for _, f := range fields {
			if !roaster.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != roaster.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(roaster.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(roaster.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(roaster.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(roaster.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(roaster.FieldLabels, field.TypeJSON)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(roaster.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Roaster{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roaster.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
