// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lesomnus/go-app/internal/ent/roaster"
)

// RoasterCreate is the builder for creating a Roaster entity.
type RoasterCreate struct {
	config
	mutation *RoasterMutation
	hooks    []Hook
}

// SetAlias sets the "alias" field.
func (_c *RoasterCreate) SetAlias(v string) *RoasterCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RoasterCreate) SetName(v string) *RoasterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *RoasterCreate) SetDesc(v string) *RoasterCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetLabels sets the "labels" field.
func (_c *RoasterCreate) SetLabels(v map[string]string) *RoasterCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *RoasterCreate) SetDateCreated(v time.Time) *RoasterCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *RoasterCreate) SetNillableDateCreated(v *time.Time) *RoasterCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoasterCreate) SetID(v uuid.UUID) *RoasterCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RoasterMutation object of the builder.
func (_c *RoasterCreate) Mutation() *RoasterMutation {
	return _c.mutation
}

// Save creates the Roaster in the database.
func (_c *RoasterCreate) Save(ctx context.Context) (*Roaster, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoasterCreate) SaveX(ctx context.Context) *Roaster {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoasterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoasterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoasterCreate) check() error {
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Roaster.alias"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Roaster.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "Roaster.desc"`)}
	}
	return nil
}

func (_c *RoasterCreate) sqlSave(ctx context.Context) (*Roaster, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoasterCreate) createSpec() (*Roaster, *sqlgraph.CreateSpec) {
	var (
		_node = &Roaster{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(roaster.Table, sqlgraph.NewFieldSpec(roaster.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(roaster.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(roaster.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(roaster.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(roaster.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(roaster.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	return _node, _spec
}

// RoasterCreateBulk is the builder for creating many Roaster entities in bulk.
type RoasterCreateBulk struct {
	config
	err      error
	builders []*RoasterCreate
}

// Save creates the Roaster entities in the database.
func (_c *RoasterCreateBulk) Save(ctx context.Context) ([]*Roaster, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Roaster, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoasterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoasterCreateBulk) SaveX(ctx context.Context) []*Roaster {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoasterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoasterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
