// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: go_app/tenant.proto

package ent

import (
	go_app "github.com/lesomnus/go-app/go_app"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Tenant) Proto() *go_app.Tenant {
	x := &go_app.Tenant{}
	x.SetId(e.ID[:])
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
