// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: go_app/holder.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/google/uuid"
	go_app "github.com/lesomnus/go-app/go_app"
	ent "github.com/lesomnus/go-app/internal/ent"
	holder "github.com/lesomnus/go-app/internal/ent/holder"
	predicate "github.com/lesomnus/go-app/internal/ent/predicate"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	time "time"
)

type HolderServiceServer struct {
	Db *ent.Client
	go_app.UnimplementedHolderServiceServer
}

func NewHolderServiceServer(db *ent.Client) go_app.HolderServiceServer {
	return HolderServiceServer{Db: db}
}

func (s HolderServiceServer) Add(ctx context.Context, req *go_app.HolderAddRequest) (*go_app.Holder, error) {
	ds := make([]func(v *go_app.Holder), 0, 1)
	q := s.Db.Holder.Create()
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			q.SetID(v)
		}
	} else {
		q.SetID(uuid.New())
	}
	if k, err := TenantGetKey(ctx, s.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantID(k)
		ds = append(ds, func(v *go_app.Holder) {
			v.SetTenant(go_app.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(time.Now().UTC())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "Holder already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "Holder: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s HolderServiceServer) Get(ctx context.Context, req *go_app.HolderGetRequest) (*go_app.Holder, error) {
	q := s.Db.Holder.Query()

	if p, err := HolderPick(req.GetRef()); err != nil {
		return nil, err
	} else {
		q.Where(p)
	}
	HolderSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Holder not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectHolderKey(q *ent.HolderQuery) {
	q.Select(holder.FieldID)
}

func HolderSelectedFields(m *go_app.HolderSelect) []string {
	if m.GetAll() {
		return holder.Columns
	}

	vs := make([]string, 0, len(holder.Columns))
	{
		vs = append(vs, holder.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, holder.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, holder.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, holder.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, holder.FieldLabels)
	}
	if m.GetDateCreated() {
		vs = append(vs, holder.FieldDateCreated)
	}

	return vs
}

func HolderSelect(q *ent.HolderQuery, m *go_app.HolderSelect) {
	if !m.GetAll() {
		fields := HolderSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func HolderSelectInit(q *ent.HolderQuery, m *go_app.HolderSelect) {
	if m != nil {
		HolderSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s HolderServiceServer) Patch(ctx context.Context, req *go_app.HolderPatchRequest) (*go_app.Holder, error) {
	p, err := HolderPick(req.GetRef())
	if err != nil {
		return nil, err
	}

	q := s.Db.Holder.Update().Where(p)
	if req.HasAlias() {
		q.SetAlias(req.GetAlias())
	}
	if req.HasName() {
		q.SetName(req.GetName())
	}
	if req.HasDesc() {
		q.SetDesc(req.GetDesc())
	}
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}

	if n, err := q.Save(ctx); err != nil {
		return nil, err
	} else if n == 0 {
		return nil, status.Errorf(codes.NotFound, "not found")
	}

	return s.Get(ctx, req.GetRef().Pick())
}

func HolderGetKey(ctx context.Context, db *ent.Client, ref *go_app.HolderRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := HolderPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Holder.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Holder not found")
		}
		return z, err
	}

	return v, nil
}

func (s HolderServiceServer) Erase(ctx context.Context, req *go_app.HolderRef) (*emptypb.Empty, error) {
	p, err := HolderPick(req)
	if err != nil {
		return nil, err
	}

	if _, err := s.Db.Holder.Delete().Where(p).Exec(ctx); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func HolderPick(req *go_app.HolderRef) (predicate.Holder, error) {
	switch req.WhichKey() {
	case go_app.HolderRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return holder.IDEQ(v), nil
		}
	case go_app.HolderRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.Holder, 0, 2)
		ps = append(ps, holder.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, holder.HasTenantWith(p))
		}
		return holder.And(ps...), nil
	case go_app.HolderRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Holder")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
