// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: go_app/holder.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	uuid "github.com/google/uuid"
	go_app "github.com/lesomnus/go-app/go_app"
	ent "github.com/lesomnus/go-app/internal/ent"
	holder "github.com/lesomnus/go-app/internal/ent/holder"
	predicate "github.com/lesomnus/go-app/internal/ent/predicate"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	time "time"
)

type HolderServiceServer struct {
	Db *ent.Client

	// Rec is told about every write this server makes, and nothing is told
	// if it is nil. See [Recorder].
	Rec Recorder

	// Scope narrows every query this server builds, and it sees every row
	// if it is nil. See [Scopes].
	Scope func(ctx context.Context) (predicate.Holder, error)

	go_app.UnimplementedHolderServiceServer
}

// NewHolderServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewHolderServiceServer(db *ent.Client, opts ...Option) go_app.HolderServiceServer {
	s := Server{Db: db}
	for _, opt := range opts {
		opt(&s)
	}
	return HolderServiceServer{Db: s.Db, Rec: s.Rec, Scope: s.Scope.Holder}
}

// HolderNarrow answers with `p` and everything else that narrows a
// read of a Holder: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func HolderNarrow(ctx context.Context, scope func(context.Context) (predicate.Holder, error), p predicate.Holder) (predicate.Holder, error) {
	ps := make([]predicate.Holder, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, holder.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return holder.And(ps...), nil
	}
}

// narrow is [HolderNarrow] with this server's own scope.
func (s HolderServiceServer) narrow(ctx context.Context, p predicate.Holder) (predicate.Holder, error) {
	return HolderNarrow(ctx, s.Scope, p)
}

func (s HolderServiceServer) Add(ctx context.Context, req *go_app.HolderAddRequest) (*go_app.Holder, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *go_app.Holder), 0, 1)
	q := st.Db.Holder.Create()
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			q.SetID(v)
		}
	} else {
		q.SetID(uuid.New())
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantID(k)
		ds = append(ds, func(v *go_app.Holder) {
			v.SetTenant(go_app.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(time.Now().UTC())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "Holder already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "Holder: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		Method: go_app.HolderService_Add_FullMethodName,
		Key:    u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s HolderServiceServer) Get(ctx context.Context, req *go_app.HolderGetRequest) (*go_app.Holder, error) {
	p, err := HolderPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Holder.Query().Where(p)
	HolderSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Holder not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectHolderKey(q *ent.HolderQuery) {
	q.Select(holder.FieldID)
}

func HolderSelectedFields(m *go_app.HolderSelect) []string {
	if m.GetAll() {
		return holder.Columns
	}

	vs := make([]string, 0, len(holder.Columns))
	{
		vs = append(vs, holder.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, holder.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, holder.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, holder.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, holder.FieldLabels)
	}
	if m.GetDateErased() {
		vs = append(vs, holder.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, holder.FieldDateCreated)
	}

	return vs
}

func HolderSelect(q *ent.HolderQuery, m *go_app.HolderSelect) {
	if !m.GetAll() {
		fields := HolderSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func HolderSelectInit(q *ent.HolderQuery, m *go_app.HolderSelect) {
	if m != nil {
		HolderSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s HolderServiceServer) Patch(ctx context.Context, req *go_app.HolderPatchRequest) (*go_app.Holder, error) {
	doc, err := ormpatch.FromPatchRequest(holderOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, go_app.HolderService_Patch_FullMethodName)
}

func HolderGetKey(ctx context.Context, db *ent.Client, ref *go_app.HolderRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := HolderPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Holder.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Holder not found")
		}
		return z, err
	}

	return v, nil
}

var holderOrmEntity = ormpatch.MustEntityOf(go_app.File_go_app_holder_proto, "Holder")

var holderPatchColumns = entpatch.Columns{
	1: holder.FieldID, 2: holder.TenantColumn, 4: holder.FieldAlias, 5: holder.FieldName, 6: holder.FieldDesc, 7: holder.FieldLabels, 14: holder.FieldDateErased, 15: holder.FieldDateCreated}

func (s HolderServiceServer) Apply(ctx context.Context, req *go_app.HolderApplyRequest) (*go_app.Holder, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), go_app.HolderService_Apply_FullMethodName)
}

func (s HolderServiceServer) apply(ctx context.Context, ref *go_app.HolderRef, doc *patchpb.Patch, method string) (*go_app.Holder, error) {
	plan := &ormpatch.Plan{Entity: holderOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(holderOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, holderPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := HolderGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &go_app.HolderRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, holder.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Holder.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Holder(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Holder.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Holder not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Holder.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Holder(pred))
		}
		q.Modify(mod)
		if n, err := q.Save(ctx); err != nil {
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Holder.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Holder not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			Method: method,
			Key:    k,
			Patch:  doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s HolderServiceServer) Erase(ctx context.Context, req *go_app.HolderRef) (*emptypb.Empty, error) {
	p, err := HolderPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Holder.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &emptypb.Empty{}, nil
			}
			return nil, err
		}

		k = v
		p = holder.IDEQ(v)
	}

	u := st.Db.Holder.Update().Where(p)
	u.SetDateErased(time.Now().UTC())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			Method: go_app.HolderService_Erase_FullMethodName,
			Key:    k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func HolderPick(req *go_app.HolderRef) (predicate.Holder, error) {
	switch req.WhichKey() {
	case go_app.HolderRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return holder.IDEQ(v), nil
		}
	case go_app.HolderRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.Holder, 0, 2)
		ps = append(ps, holder.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, holder.HasTenantWith(p))
		}
		return holder.And(ps...), nil
	case go_app.HolderRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Holder")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
