// Code generated by protoc-gen-orm-ent. DO NOT EDIT.

package bare

import (
	go_app "github.com/lesomnus/go-app/go_app"
	ent "github.com/lesomnus/go-app/internal/ent"
)

type Server struct {
	Db *ent.Client
}

func NewServer(db *ent.Client) Server {
	return Server{Db: db}
}

func (s Server) Tenant() go_app.TenantServiceServer { return NewTenantServiceServer(s.Db) }
func (s Server) User() go_app.UserServiceServer     { return NewUserServiceServer(s.Db) }
