// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: go_app/user.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/google/uuid"
	go_app "github.com/lesomnus/go-app/go_app"
	ent "github.com/lesomnus/go-app/internal/ent"
	predicate "github.com/lesomnus/go-app/internal/ent/predicate"
	user "github.com/lesomnus/go-app/internal/ent/user"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	time "time"
)

type UserServiceServer struct {
	Db *ent.Client
	go_app.UnimplementedUserServiceServer
}

func NewUserServiceServer(db *ent.Client) go_app.UserServiceServer {
	return UserServiceServer{Db: db}
}

func (s UserServiceServer) Add(ctx context.Context, req *go_app.UserAddRequest) (*go_app.User, error) {
	ds := make([]func(v *go_app.User), 0, 1)
	q := s.Db.User.Create()
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			q.SetID(v)
		}
	} else {
		q.SetID(uuid.New())
	}
	if k, err := TenantGetKey(ctx, s.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantID(k)
		ds = append(ds, func(v *go_app.User) {
			v.SetTenant(go_app.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(time.Now().UTC())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "User already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "User: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s UserServiceServer) Get(ctx context.Context, req *go_app.UserGetRequest) (*go_app.User, error) {
	q := s.Db.User.Query()

	if p, err := UserPick(req.GetRef()); err != nil {
		return nil, err
	} else {
		q.Where(p)
	}
	UserSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "User not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectUserKey(q *ent.UserQuery) {
	q.Select(user.FieldID)
}

func UserSelectedFields(m *go_app.UserSelect) []string {
	if m.GetAll() {
		return user.Columns
	}

	vs := make([]string, 0, len(user.Columns))
	{
		vs = append(vs, user.FieldID)
	}
	if m.GetAlias() {
		vs = append(vs, user.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, user.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, user.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, user.FieldLabels)
	}
	if m.GetDateCreated() {
		vs = append(vs, user.FieldDateCreated)
	}

	return vs
}

func UserSelect(q *ent.UserQuery, m *go_app.UserSelect) {
	if !m.GetAll() {
		fields := UserSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func UserSelectInit(q *ent.UserQuery, m *go_app.UserSelect) {
	if m != nil {
		UserSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s UserServiceServer) Patch(ctx context.Context, req *go_app.UserPatchRequest) (*go_app.User, error) {
	p, err := UserPick(req.GetRef())
	if err != nil {
		return nil, err
	}

	q := s.Db.User.Update().Where(p)
	if req.HasAlias() {
		q.SetAlias(req.GetAlias())
	}
	if req.HasName() {
		q.SetName(req.GetName())
	}
	if req.HasDesc() {
		q.SetDesc(req.GetDesc())
	}
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}

	if n, err := q.Save(ctx); err != nil {
		return nil, err
	} else if n == 0 {
		return nil, status.Errorf(codes.NotFound, "not found")
	}

	return s.Get(ctx, req.GetRef().Pick())
}

func UserGetKey(ctx context.Context, db *ent.Client, ref *go_app.UserRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := UserPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.User.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "User not found")
		}
		return z, err
	}

	return v, nil
}

func (s UserServiceServer) Erase(ctx context.Context, req *go_app.UserRef) (*emptypb.Empty, error) {
	p, err := UserPick(req)
	if err != nil {
		return nil, err
	}

	if _, err := s.Db.User.Delete().Where(p).Exec(ctx); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func UserPick(req *go_app.UserRef) (predicate.User, error) {
	switch req.WhichKey() {
	case go_app.UserRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return user.IDEQ(v), nil
		}
	case go_app.UserRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.User, 0, 2)
		ps = append(ps, user.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, user.HasTenantWith(p))
		}
		return user.And(ps...), nil
	case go_app.UserRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: User")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
