#!/usr/bin/env bash

set -o errexit
set -o pipefail

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # Directory where this script exists.
__root="$(cd "$(dirname "${__dir}")" && pwd)"         # Root directory of project.

# The ent schema is generated by protoc-gen-orm-ent (see `scripts/gen-go.sh`);
# this turns it into the ent runtime the generated servers run against.
#
# The target must stay next to the schema because the servers import the ent
# package as "<message package>/internal/ent", which is how it is spelled in
# `ent.namer` of buf.gen.yaml.
SCHEMA_DIR="${SCHEMA_DIR:-${__root}/internal/ent/schema}"
TARGET_DIR="${TARGET_DIR:-${__root}/internal/ent}"

cd "${__root}"
go tool ent generate "${SCHEMA_DIR}" --target "${TARGET_DIR}"

echo "Done."
